export type { StdModule } from './types'
export { ModuleRegistry } from './module-registry'
export type { DependencyEdge, DependencyResolver } from '../../../core/dependency-resolver'

import type { StdModule } from './types'
import { ModuleRegistry } from './module-registry'
import { componentComponentMappings } from '../../../core/component/registry'

/**
 * 標準函式庫模組清單。
 *
 * ## ⚠️ **今天這裡只剩名字**（2026-08-11，F 完成之後的清掃）
 *
 * 這份清單原本每一列都掛著三個註冊函式與兩份宣告。F 把 177 顆元件全部搬進
 * 膠囊之後：
 *
 * ```
 * 43 個註冊函式        全部是空的       → 刪掉（其中 38 個檔除了空殼什麼都沒有）
 * 17 份 components.json  全部是空陣列     → 刪掉
 * 17 份 blocks.json    全部是空陣列     → 刪掉
 * ```
 *
 * **而模組本身不能刪**——`header` 是**工具箱段落的鍵**
 * （`toolbox-categories.ts` 寫著 `{ from: '<cstdio>' }`）。
 * 刪掉的話那些段落會整批回傳零筆，而可拿性護欄會說「使用者拿不到」
 * ——2026-08-11 試刪 `<cstring>`／`<cctype>` 時當場驗證過。
 *
 * > **模組是搬家的中途站，不是終點——而中途站的最後一塊石頭是它的名字。**
 *
 * ⚠️ 那個名字今天同時扮演兩個角色：**標頭檔**（`#include` 解析）與
 * **工具箱段落**。兩者剛好一致，而那是巧合不是設計
 * ——`owner` 與 `requires` 那件事已經踩過同一個形狀。
 * 見 `draft/2026-08-11-universal是一份還沒被驗證的外延主張.md`。
 */
export const allStdModules: StdModule[] = [
  { header: '<iostream>', components: [], blocks: [] },
  { header: '<cstring>', components: [], blocks: [] },
  { header: '<cstdio>', components: [], blocks: [] },
  { header: '<vector>', components: [], blocks: [] },
  { header: '<algorithm>', components: [], blocks: [] },
  { header: '<string>', components: [], blocks: [] },
  { header: '<map>', components: [], blocks: [] },
  { header: '<stack>', components: [], blocks: [] },
  { header: '<queue>', components: [], blocks: [] },
  { header: '<set>', components: [], blocks: [] },
  { header: '<cmath>', components: [], blocks: [] },
  { header: '<cstdlib>', components: [], blocks: [] },
  { header: '<cctype>', components: [], blocks: [] },
  { header: '<numeric>', components: [], blocks: [] },
  { header: '<sstream>', components: [], blocks: [] },
  { header: '<fstream>', components: [], blocks: [] },
  { header: '<utility>', components: [], blocks: [] },
]

export function createPopulatedRegistry(): ModuleRegistry {
  const registry = new ModuleRegistry()
  for (const mod of allStdModules) {
    registry.register(mod)
  }
  // Universal I/O components — not in any components.json but generated by iostream
  // 元件膠囊的依賴——它們不屬於任何 std 模組，所以走這個既有的機制
  // （`cpp:print` → `<iostream>` 從一開始就是這樣掛的）。
  for (const [componentId, header] of componentComponentMappings()) {
    registry.registerComponentMapping(componentId, header)
  }
  return registry
}
