/**
 * Fuzz tests for C++ strings (hard difficulty).
 *
 * Programs generated by an isolated instructor agent covering:
 * - Palindrome detection (character access with [])
 * - Character frequency with map
 * - Word-by-word string reversal
 * - Substring palindrome finding
 * - Recursive string reversal
 * - Run-length encoding
 * - String rotation and isRotation
 * - Vowel/consonant analysis
 * - Longest common prefix
 * - replaceAll (find + replace)
 *
 * Key concept under test: cpp_string_at (str[i] character access)
 * - Lift: str[i] degrades to array_access (no dedicated lifter — expected)
 * - Generate: cpp_string_at node → str[i] (tested in unit tests)
 *
 * Each test verifies:
 *   1. lift → generate round-trip produces compilable, semantically equivalent code
 *   2. EXPECTED_DEGRADATION noted for programs using unsupported features
 */
import { describe, it, expect, beforeAll } from 'vitest'
import { Parser, Language } from 'web-tree-sitter'
import { createTestLifter } from '../helpers/setup-lifter'
import type { Lifter } from '../../src/core/lift/lifter'
import { registerCppLanguage } from '../../src/languages/cpp/generators'
import { generateCode } from '../../src/core/projection/code-generator'
import { setupTestRenderer } from '../helpers/setup-renderer'
import { execSync } from 'child_process'
import { writeFileSync, mkdirSync } from 'fs'
import type { StylePreset } from '../../src/core/types'
import type { SemanticNode } from '../../src/core/semantic-tree'

const style: StylePreset = {
  id: 'apcs', name: { 'zh-TW': 'APCS', en: 'APCS' },
  io_style: 'cout', naming_convention: 'camelCase',
  indent_size: 4, brace_style: 'K&R',
  namespace_style: 'using', header_style: 'individual',
}

let tsParser: Parser
let lifter: Lifter

beforeAll(async () => {
  await Parser.init({
    locateFile: (s: string) => `${process.cwd()}/public/${s}`,
  })
  tsParser = new Parser()
  const lang = await Language.load(`${process.cwd()}/public/tree-sitter-cpp.wasm`)
  tsParser.setLanguage(lang)
  lifter = createTestLifter()
  registerCppLanguage()
  setupTestRenderer()
})

function liftCode(code: string): SemanticNode | null {
  const tree = tsParser.parse(code)
  return lifter.lift(tree.rootNode as any)
}

function collectConcepts(node: SemanticNode | null, result: Set<string> = new Set()): Set<string> {
  if (!node) return result
  result.add(node.concept)
  for (const children of Object.values(node.children ?? {})) {
    for (const child of children as SemanticNode[]) {
      collectConcepts(child, result)
    }
  }
  return result
}

function runCpp(code: string): string | null {
  try {
    mkdirSync('/tmp/semorphe-fuzz', { recursive: true })
    const src = `/tmp/semorphe-fuzz/rt_${Date.now()}_${Math.floor(Math.random() * 10000)}.cpp`
    const bin = src.replace('.cpp', '')
    writeFileSync(src, code)
    execSync(`g++ -std=c++17 -o ${bin} ${src}`, { encoding: 'utf-8', stdio: 'pipe' })
    return execSync(bin, { encoding: 'utf-8', timeout: 5000 })
  } catch {
    return null
  }
}

// ─── fuzz_1: 迴文偵測（palindrome word check） ────────────────────────────────

describe('fuzz_1: palindrome detection with str[i] access', () => {
  const code = `#include <iostream>
#include <string>
#include <vector>
using namespace std;

bool isPalindrome(const string& s) {
    int n = s.length();
    for (int i = 0; i < n / 2; i++) {
        if (s[i] != s[n - 1 - i]) return false;
    }
    return true;
}

vector<string> splitWords(const string& sentence) {
    vector<string> words;
    string word;
    for (char c : sentence) {
        if (c == ' ') {
            if (!word.empty()) { words.push_back(word); word = ""; }
        } else {
            word += c;
        }
    }
    if (!word.empty()) words.push_back(word);
    return words;
}

int main() {
    string sentence = "racecar level hello madam world";
    vector<string> words = splitWords(sentence);
    for (const string& w : words) {
        cout << w << ": " << (isPalindrome(w) ? "palindrome" : "not palindrome") << "\\n";
    }
    return 0;
}`

  it('should lift without null (fuzz_1)', () => {
    const tree = liftCode(code)
    expect(tree).not.toBeNull()
  })

  it.skip('fuzz_1: round-trip stable and output matches (SEMANTIC_DIFF — pre-existing bug)', () => {
    // BUG: vector<string> declaration with function call initializer is not lifted correctly.
    // `vector<string> words = splitWords(sentence)` → lifter produces `cpp_vector_declare`
    // but the initializer (call_expression) is dropped, so the variable is declared empty.
    // Root cause: liftVectorDeclaration does not handle init_declarator with a call_expression.
    // Fix: support call_expression as initializer in cpp_vector_declare lifter.
    // When to fix: when vector initializer support is implemented.
    const tree = liftCode(code)
    expect(tree).not.toBeNull()
    const gen1 = generateCode(tree!, 'cpp', style)
    const gen2 = generateCode(liftCode(gen1)!, 'cpp', style)
    expect(gen1).toBe(gen2)
    const actual = runCpp(gen1)
    const expected = runCpp(code)
    expect(actual).not.toBeNull()
    expect(actual?.trim()).toBe(expected?.trim())
  })
})

// ─── fuzz_2: 字元頻率統計（map<char,int>） ────────────────────────────────────

describe('fuzz_2: character frequency with map', () => {
  const code = `#include <iostream>
#include <string>
#include <map>
using namespace std;

int main() {
    string s = "programming";
    map<char, int> freq;
    for (char c : s) freq[c]++;
    for (auto& p : freq) {
        if (p.second > 1) {
            cout << p.first << ": " << p.second << "\\n";
        }
    }
    return 0;
}`

  it('should lift without null (fuzz_2)', () => {
    const tree = liftCode(code)
    expect(tree).not.toBeNull()
  })

  it('fuzz_2: round-trip stable (EXPECTED_DEGRADATION — map iteration, auto)', () => {
    // map<char,int> and "for (auto& p : freq)" use features that may degrade
    const tree = liftCode(code)
    expect(tree).not.toBeNull()
    const gen1 = generateCode(tree!, 'cpp', style)
    const gen2 = generateCode(liftCode(gen1)!, 'cpp', style)
    expect(gen1).toBe(gen2)
    const actual = runCpp(gen1)
    const expected = runCpp(code)
    expect(actual).not.toBeNull()
    expect(actual?.trim()).toBe(expected?.trim())
  })
})

// ─── fuzz_3: 單詞逆轉（word reversal with swap and str[i]） ────────────────────

describe('fuzz_3: word reversal with str[i] and swap', () => {
  const code = `#include <iostream>
#include <string>
#include <vector>
using namespace std;

string reverseWord(const string& w) {
    string r = w;
    int lo = 0, hi = r.length() - 1;
    while (lo < hi) { swap(r[lo++], r[hi--]); }
    return r;
}

int main() {
    string sentence = "the quick brown fox";
    string result, word;
    for (int i = 0; i <= (int)sentence.size(); i++) {
        if (i == (int)sentence.size() || sentence[i] == ' ') {
            if (!word.empty()) {
                if (!result.empty()) result += ' ';
                result += reverseWord(word);
                word = "";
            }
        } else {
            word += sentence[i];
        }
    }
    cout << result << "\\n";
    return 0;
}`

  it('should lift without null (fuzz_3)', () => {
    const tree = liftCode(code)
    expect(tree).not.toBeNull()
  })

  it.skip('fuzz_3: round-trip stable and output matches (COMPILE_FAIL — pre-existing bug)', () => {
    // BUG: multi-variable declaration `string result, word;` only generates `string result;`.
    // The second declarator `word` is silently dropped by the lifter.
    // Root cause: liftDeclaration only processes the first init_declarator in a
    // declaration_specifier with multiple declarators (comma-separated).
    // Fix: produce multiple cpp_string_declare nodes for comma-separated declarators.
    // When to fix: when multi-var declaration support is implemented.
    const tree = liftCode(code)
    expect(tree).not.toBeNull()
    const gen1 = generateCode(tree!, 'cpp', style)
    const gen2 = generateCode(liftCode(gen1)!, 'cpp', style)
    expect(gen1).toBe(gen2)
    const actual = runCpp(gen1)
    const expected = runCpp(code)
    expect(actual).not.toBeNull()
    expect(actual?.trim()).toBe(expected?.trim())
  })
})

// ─── fuzz_4: 子字串迴文（substr palindrome with str[l]/str[r]） ──────────────

describe('fuzz_4: substring palindromes with str[l]/str[r] access', () => {
  const code = `#include <iostream>
#include <string>
#include <vector>
using namespace std;

bool isPalin(const string& s, int l, int r) {
    while (l < r) {
        if (s[l] != s[r]) return false;
        l++; r--;
    }
    return true;
}

int main() {
    string s = "abacaba";
    vector<string> found;
    int n = s.length();
    for (int i = 0; i < n; i++) {
        for (int j = i + 2; j < n; j++) {
            if (isPalin(s, i, j)) {
                found.push_back(s.substr(i, j - i + 1));
            }
        }
    }
    for (const string& p : found) cout << p << "\\n";
    return 0;
}`

  it('should lift without null (fuzz_4)', () => {
    const tree = liftCode(code)
    expect(tree).not.toBeNull()
  })

  it('fuzz_4: round-trip stable and output matches (PASS)', () => {
    const tree = liftCode(code)
    expect(tree).not.toBeNull()
    const gen1 = generateCode(tree!, 'cpp', style)
    const gen2 = generateCode(liftCode(gen1)!, 'cpp', style)
    expect(gen1).toBe(gen2)
    const actual = runCpp(gen1)
    const expected = runCpp(code)
    expect(actual).not.toBeNull()
    expect(actual?.trim()).toBe(expected?.trim())
  })
})

// ─── fuzz_5: 遞迴反轉（recursive reversal with s[idx]） ──────────────────────

describe('fuzz_5: recursive string reverse with s[idx]', () => {
  const code = `#include <iostream>
#include <string>
#include <vector>
using namespace std;

string reverseStr(const string& s, int idx) {
    if (idx == (int)s.size()) return "";
    return reverseStr(s, idx + 1) + s[idx];
}

bool isPalin(const string& s) {
    return s == reverseStr(s, 0);
}

int main() {
    vector<string> tests = {"racecar", "hello", "abba", "world", "noon"};
    for (const string& t : tests) {
        cout << t << " -> " << (isPalin(t) ? "yes" : "no") << "\\n";
    }
    return 0;
}`

  it('should lift without null (fuzz_5)', () => {
    const tree = liftCode(code)
    expect(tree).not.toBeNull()
  })

  it.skip('fuzz_5: round-trip stable and output matches (SEMANTIC_DIFF — pre-existing bug)', () => {
    // BUG: vector<string> with brace-initializer `= {"racecar", "hello", ...}` is not lifted.
    // The initializer_list (brace-init) is dropped; the variable is declared empty.
    // Root cause: liftVectorDeclaration does not handle initializer_list syntax.
    // Fix: support initializer_list as initializer in cpp_vector_declare lifter.
    // When to fix: when vector initializer support is implemented.
    const tree = liftCode(code)
    expect(tree).not.toBeNull()
    const gen1 = generateCode(tree!, 'cpp', style)
    const gen2 = generateCode(liftCode(gen1)!, 'cpp', style)
    expect(gen1).toBe(gen2)
    const actual = runCpp(gen1)
    const expected = runCpp(code)
    expect(actual).not.toBeNull()
    expect(actual?.trim()).toBe(expected?.trim())
  })
})

// ─── fuzz_6: 遊程長度編碼（RLE encoding with s[i] and s[i-1]） ───────────────

describe('fuzz_6: run-length encoding with s[i] and s[i-1]', () => {
  const code = `#include <iostream>
#include <string>
using namespace std;

string rleEncode(const string& s) {
    if (s.empty()) return "";
    string result;
    int count = 1;
    for (int i = 1; i <= (int)s.size(); i++) {
        if (i < (int)s.size() && s[i] == s[i-1]) {
            count++;
        } else {
            result += s[i-1];
            if (count > 1) result += to_string(count);
            count = 1;
        }
    }
    return result;
}

int main() {
    string inputs[] = {"aaabbbcc", "abcd", "aaaaaa", "aabbaa"};
    for (const string& s : inputs) {
        cout << s << " -> " << rleEncode(s) << "\\n";
    }
    return 0;
}`

  it('should lift without null (fuzz_6)', () => {
    const tree = liftCode(code)
    expect(tree).not.toBeNull()
  })

  it('fuzz_6: round-trip stable and output matches (PASS)', () => {
    const tree = liftCode(code)
    expect(tree).not.toBeNull()
    const gen1 = generateCode(tree!, 'cpp', style)
    const gen2 = generateCode(liftCode(gen1)!, 'cpp', style)
    expect(gen1).toBe(gen2)
    const actual = runCpp(gen1)
    const expected = runCpp(code)
    expect(actual).not.toBeNull()
    expect(actual?.trim()).toBe(expected?.trim())
  })
})

// ─── fuzz_7: 字串旋轉（rotation with substr + find） ─────────────────────────

describe('fuzz_7: string rotation with substr and find', () => {
  const code = `#include <iostream>
#include <string>
using namespace std;

string rotateLeft(const string& s, int k) {
    int n = s.length();
    if (n == 0) return s;
    k = k % n;
    return s.substr(k) + s.substr(0, k);
}

bool isRotation(const string& a, const string& b) {
    if (a.length() != b.length()) return false;
    string doubled = a + a;
    return doubled.find(b) != string::npos;
}

int main() {
    string s = "abcdef";
    for (int k = 0; k <= 3; k++) {
        cout << "rotate " << k << ": " << rotateLeft(s, k) << "\\n";
    }
    cout << isRotation("abcdef", "cdefab") << "\\n";
    cout << isRotation("abcdef", "abcfed") << "\\n";
    return 0;
}`

  it('should lift without null (fuzz_7)', () => {
    const tree = liftCode(code)
    expect(tree).not.toBeNull()
  })

  it('fuzz_7: round-trip stable and output matches (PASS)', () => {
    const tree = liftCode(code)
    expect(tree).not.toBeNull()
    const gen1 = generateCode(tree!, 'cpp', style)
    const gen2 = generateCode(liftCode(gen1)!, 'cpp', style)
    expect(gen1).toBe(gen2)
    const actual = runCpp(gen1)
    const expected = runCpp(code)
    expect(actual).not.toBeNull()
    expect(actual?.trim()).toBe(expected?.trim())
  })
})

// ─── fuzz_8: 母音子音分析（vowel/consonant with sentence[i]） ─────────────────

describe('fuzz_8: vowel/consonant analysis with sentence[i]', () => {
  const code = `#include <iostream>
#include <string>
#include <cctype>
using namespace std;

bool isVowel(char c) {
    c = tolower(c);
    return c=='a'||c=='e'||c=='i'||c=='o'||c=='u';
}

void analyzeWord(const string& w) {
    int v = 0, con = 0;
    for (char c : w) {
        if (isalpha(c)) {
            if (isVowel(c)) v++;
            else con++;
        }
    }
    cout << w << ": vowels=" << v << " consonants=" << con << "\\n";
}

int main() {
    string sentence = "Hello World Strings Are Tricky";
    string word;
    for (int i = 0; i <= (int)sentence.size(); i++) {
        if (i == (int)sentence.size() || sentence[i] == ' ') {
            if (!word.empty()) { analyzeWord(word); word = ""; }
        } else {
            word += sentence[i];
        }
    }
    return 0;
}`

  it('should lift without null (fuzz_8)', () => {
    const tree = liftCode(code)
    expect(tree).not.toBeNull()
  })

  it('fuzz_8: round-trip stable and output matches (PASS)', () => {
    const tree = liftCode(code)
    expect(tree).not.toBeNull()
    const gen1 = generateCode(tree!, 'cpp', style)
    const gen2 = generateCode(liftCode(gen1)!, 'cpp', style)
    expect(gen1).toBe(gen2)
    const actual = runCpp(gen1)
    const expected = runCpp(code)
    expect(actual).not.toBeNull()
    expect(actual?.trim()).toBe(expected?.trim())
  })
})

// ─── fuzz_9: 最長公共前綴（LCP with prefix[j] and strs[i][j]） ───────────────

describe('fuzz_9: longest common prefix with str[i][j] access', () => {
  const code = `#include <iostream>
#include <string>
#include <vector>
using namespace std;

string longestCommonPrefix(const vector<string>& strs) {
    if (strs.empty()) return "";
    string prefix = strs[0];
    for (int i = 1; i < (int)strs.size(); i++) {
        int j = 0;
        while (j < (int)prefix.size() && j < (int)strs[i].size() && prefix[j] == strs[i][j]) {
            j++;
        }
        prefix = prefix.substr(0, j);
        if (prefix.empty()) return "";
    }
    return prefix;
}

int main() {
    vector<string> v1 = {"flower", "flow", "flight"};
    vector<string> v2 = {"dog", "racecar", "car"};
    vector<string> v3 = {"interview", "interact", "interface", "internal"};
    cout << "\\"" << longestCommonPrefix(v1) << "\\"\\n";
    cout << "\\"" << longestCommonPrefix(v2) << "\\"\\n";
    cout << "\\"" << longestCommonPrefix(v3) << "\\"\\n";
    return 0;
}`

  it('should lift without null (fuzz_9)', () => {
    const tree = liftCode(code)
    expect(tree).not.toBeNull()
  })

  it.skip('fuzz_9: round-trip stable and output matches (SEMANTIC_DIFF — pre-existing bug)', () => {
    // BUG: vector<string> brace-initializer `= {"flower", "flow", "flight"}` is not lifted.
    // All three vectors v1/v2/v3 end up empty; the LCP function receives empty containers
    // and always returns "".
    // Root cause: same as fuzz_5 — liftVectorDeclaration does not handle initializer_list.
    // Fix: support initializer_list as initializer in cpp_vector_declare lifter.
    // When to fix: when vector initializer support is implemented.
    const tree = liftCode(code)
    expect(tree).not.toBeNull()
    const gen1 = generateCode(tree!, 'cpp', style)
    const gen2 = generateCode(liftCode(gen1)!, 'cpp', style)
    expect(gen1).toBe(gen2)
    const actual = runCpp(gen1)
    const expected = runCpp(code)
    expect(actual).not.toBeNull()
    expect(actual?.trim()).toBe(expected?.trim())
  })
})

// ─── fuzz_10: replaceAll（find + replace loop） ───────────────────────────────

describe('fuzz_10: replaceAll with find and replace', () => {
  const code = `#include <iostream>
#include <string>
using namespace std;

string replaceAll(string s, const string& from, const string& to) {
    if (from.empty()) return s;
    size_t pos = 0;
    while ((pos = s.find(from, pos)) != string::npos) {
        s.replace(pos, from.length(), to);
        pos += to.length();
    }
    return s;
}

int main() {
    cout << replaceAll("hello world", "world", "there") << "\\n";
    cout << replaceAll("aaa", "aa", "b") << "\\n";
    cout << replaceAll("abcabcabc", "abc", "X") << "\\n";
    cout << replaceAll("no match here", "xyz", "!") << "\\n";
    return 0;
}`

  it('should lift without null (fuzz_10)', () => {
    const tree = liftCode(code)
    expect(tree).not.toBeNull()
  })

  it.skip('fuzz_10: round-trip stable and output matches (COMPILE_FAIL — pre-existing bug)', () => {
    // BUG: `while ((pos = s.find(from, pos)) != string::npos)` generates malformed code.
    // The assignment-inside-while-condition pattern is not handled by liftWhile.
    // The condition expression involves a method call with 2 args and assignment; the lifter
    // cannot parse this compound condition and falls back to raw_code for the whole while loop.
    // Root cause: liftWhile expects simple binary/comparison conditions, not assignment-chains.
    // Fix: detect assignment-in-condition pattern and treat as raw_code or add dedicated lifter.
    // When to fix: when assignment-in-while-condition support is implemented.
    const tree = liftCode(code)
    expect(tree).not.toBeNull()
    const gen1 = generateCode(tree!, 'cpp', style)
    const gen2 = generateCode(liftCode(gen1)!, 'cpp', style)
    expect(gen1).toBe(gen2)
    const actual = runCpp(gen1)
    const expected = runCpp(code)
    expect(actual).not.toBeNull()
    expect(actual?.trim()).toBe(expected?.trim())
  })
})
