/**
 * Fuzz Test Regression: C++ Functions & I/O
 * Generated from Phase 3 fuzz testing (2026-03-12)
 *
 * Tests lift -> generate -> execution roundtrip for programs
 * generated by an isolated agent with no knowledge of Semorphe internals.
 */
import { describe, it, expect, beforeAll } from 'vitest'
import { Parser, Language } from 'web-tree-sitter'
import type { Lifter } from '../../src/core/lift/lifter'
import { registerCppLanguage } from '../../src/languages/cpp/generators'
import { generateCode } from '../../src/core/projection/code-generator'
import { setupTestRenderer } from '../helpers/setup-renderer'
import { createTestLifter } from '../helpers/setup-lifter'
import { SemanticInterpreter } from '../../src/interpreter/interpreter'
import type { StylePreset } from '../../src/core/types'

const style: StylePreset = {
  id: 'apcs',
  name: { 'zh-TW': 'APCS', en: 'APCS' },
  io_style: 'cout',
  naming_convention: 'camelCase',
  indent_size: 4,
  brace_style: 'K&R',
  namespace_style: 'using',
  header_style: 'individual',
}

let tsParser: Parser
let lifter: Lifter

beforeAll(async () => {
  await Parser.init({
    locateFile: (scriptName: string) => `${process.cwd()}/public/${scriptName}`,
  })
  tsParser = new Parser()
  const lang = await Language.load(`${process.cwd()}/public/tree-sitter-cpp.wasm`)
  tsParser.setLanguage(lang)
  lifter = createTestLifter()
  registerCppLanguage()
  setupTestRenderer()
})

async function runCode(code: string) {
  const tree = tsParser.parse(code)
  const sem = lifter.lift(tree.rootNode as any)
  expect(sem).not.toBeNull()
  const interp = new SemanticInterpreter({ maxSteps: 100000 })
  await interp.execute(sem!, [])
  return interp
}

function roundTrip(code: string): string {
  const tree = tsParser.parse(code)
  const sem = lifter.lift(tree.rootNode as any)
  expect(sem).not.toBeNull()
  return generateCode(sem!, 'cpp', style)
}

// --- PASS programs ---

describe('fuzz: void function with side effects', () => {
  const code = `#include <iostream>
using namespace std;
int total = 0;
void addToTotal(int x) {
    total = total + x;
}
int main() {
    addToTotal(10);
    addToTotal(20);
    addToTotal(30);
    cout << total << endl;
    return 0;
}`

  it('executes correctly', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('60')
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

describe('fuzz: recursive fibonacci', () => {
  const code = `#include <iostream>
using namespace std;
int fib(int n) {
    if (n <= 0) {
        return 0;
    }
    if (n == 1) {
        return 1;
    }
    return fib(n - 1) + fib(n - 2);
}
int main() {
    cout << fib(7) << endl;
    return 0;
}`

  it('executes correctly', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('13')
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

describe('fuzz: multi-parameter function', () => {
  const code = `#include <iostream>
using namespace std;
int clamp(int val, int lo, int hi) {
    if (val < lo) {
        return lo;
    }
    if (val > hi) {
        return hi;
    }
    return val;
}
int main() {
    cout << clamp(-5, 0, 10) << endl;
    cout << clamp(7, 0, 10) << endl;
    cout << clamp(15, 0, 10) << endl;
    return 0;
}`

  it('executes correctly', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('0')
    expect(out).toContain('7')
    expect(out).toContain('10')
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

describe('fuzz: nested function calls in expression', () => {
  const code = `#include <iostream>
using namespace std;
int double_val(int x) {
    return x * 2;
}
int add(int a, int b) {
    return a + b;
}
int main() {
    int result = add(double_val(3), double_val(4));
    cout << result << endl;
    return 0;
}`

  it('executes correctly', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('14')
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

describe('fuzz: functions calling other functions', () => {
  const code = `#include <iostream>
using namespace std;
int multiply(int a, int b) {
    return a * b;
}
int cube(int x) {
    return multiply(multiply(x, x), x);
}
int main() {
    cout << cube(3) << endl;
    cout << cube(4) << endl;
    return 0;
}`

  it('executes correctly', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('27')
    expect(out).toContain('64')
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

describe('fuzz: return in different branches', () => {
  const code = `#include <iostream>
using namespace std;
int sign(int x) {
    if (x > 0) {
        return 1;
    } else if (x < 0) {
        return -1;
    } else {
        return 0;
    }
}
int main() {
    cout << sign(42) << endl;
    cout << sign(-7) << endl;
    cout << sign(0) << endl;
    return 0;
}`

  it('executes correctly', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('1')
    expect(out).toContain('-1')
    expect(out).toContain('0')
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

describe('fuzz: recursive gcd', () => {
  const code = `#include <iostream>
using namespace std;
int gcd(int a, int b) {
    if (b == 0) {
        return a;
    }
    return gcd(b, a % b);
}
int main() {
    cout << gcd(12, 8) << endl;
    cout << gcd(35, 14) << endl;
    return 0;
}`

  it('executes correctly', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('4')
    expect(out).toContain('7')
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

// --- Known issues (regression) ---

describe.skip('fuzz: char literal in function return (fixed)', () => {
  it.todo('char literal roundtrips correctly through function return')
})
