/**
 * Fuzz Test Regression: C++ Types & Advanced Ops
 * Generated from Phase 5 fuzz testing (2026-03-13)
 *
 * Tests lift → generate → execution roundtrip for programs
 * generated by an isolated agent with no knowledge of Semorphe internals.
 */
import { describe, it, expect, beforeAll } from 'vitest'
import { Parser, Language } from 'web-tree-sitter'
import type { Lifter } from '../../src/core/lift/lifter'
import { registerCppLanguage } from '../../src/languages/cpp/generators'
import { generateCode } from '../../src/core/projection/code-generator'
import { setupTestRenderer } from '../helpers/setup-renderer'
import { createTestLifter } from '../helpers/setup-lifter'
import { SemanticInterpreter } from '../../src/interpreter/interpreter'
import type { StylePreset, SemanticNode } from '../../src/core/types'

const style: StylePreset = {
  id: 'apcs',
  name: { 'zh-TW': 'APCS', en: 'APCS' },
  io_style: 'cout',
  naming_convention: 'camelCase',
  indent_size: 4,
  brace_style: 'K&R',
  namespace_style: 'using',
  header_style: 'individual',
}

let tsParser: Parser
let lifter: Lifter

beforeAll(async () => {
  await Parser.init({
    locateFile: (scriptName: string) => `${process.cwd()}/public/${scriptName}`,
  })
  tsParser = new Parser()
  const lang = await Language.load(`${process.cwd()}/public/tree-sitter-cpp.wasm`)
  tsParser.setLanguage(lang)
  lifter = createTestLifter()
  registerCppLanguage()
  setupTestRenderer()
})

async function runCode(code: string) {
  const tree = tsParser.parse(code)
  const sem = lifter.lift(tree.rootNode as any)
  expect(sem).not.toBeNull()
  const interp = new SemanticInterpreter({ maxSteps: 100000 })
  await interp.execute(sem!, [])
  return interp
}

function roundTrip(code: string): string {
  const tree = tsParser.parse(code)
  const sem = lifter.lift(tree.rootNode as any)
  expect(sem).not.toBeNull()
  return generateCode(sem!, 'cpp', style)
}

function assertStableRoundtrip(code: string) {
  const gen1 = roundTrip(code)
  const gen2 = roundTrip(gen1)
  expect(gen2).toBe(gen1)
  return gen1
}

function hasNoComponent(node: SemanticNode, forbidden: string[]): boolean {
  if (forbidden.includes(node.componentId)) return false
  for (const children of Object.values(node.children || {})) {
    for (const child of children) {
      if (!hasNoComponent(child, forbidden)) return false
    }
  }
  return true
}

// ─── PASS programs ───

describe('Fuzz: C++ Types & Advanced Ops', () => {
  it('fuzz_1: integer division and modulo', () => {
    const code = `#include <iostream>
using namespace std;

int main() {
    int a = 7, b = -3;
    int q = a / b;
    int r = a % b;
    cout << q << endl;
    cout << r << endl;
    cout << (-7 / 2) << endl;
    cout << (-7 % 2) << endl;
    cout << (13 % -5) << endl;
    return 0;
}`
    assertStableRoundtrip(code)
  })

  it('fuzz_2: operator precedence', () => {
    const code = `#include <iostream>
using namespace std;

int main() {
    int x = 2 + 3 * 4;
    cout << x << endl;
    int y = 1 | 2 & 3;
    cout << y << endl;
    int z = 5 > 3 + 1;
    cout << z << endl;
    int w = 2 << 1 + 1;
    cout << w << endl;
    bool b = 3 & 1 == 1;
    cout << b << endl;
    return 0;
}`
    assertStableRoundtrip(code)
  })

  it('fuzz_3: type coercion', () => {
    const code = `#include <iostream>
using namespace std;

int main() {
    int a = 5;
    double b = 2.0;
    cout << a / 2 << endl;
    cout << a / b << endl;
    char c = 'A';
    int d = c + 1;
    cout << d << endl;
    cout << static_cast<char>(d) << endl;
    double e = 1 / 3;
    cout << e << endl;
    double f = 1.0 / 3;
    cout << f << endl;
    return 0;
}`
    assertStableRoundtrip(code)
  })

  it('fuzz_4: compound assignment and increment', () => {
    const code = `#include <iostream>
using namespace std;

int main() {
    int x = 10;
    x += 5;
    cout << x << endl;
    x -= 3;
    cout << x << endl;
    x *= 2;
    cout << x << endl;
    x /= 3;
    cout << x << endl;
    int a = 5;
    int b = a++;
    cout << a << " " << b << endl;
    int c = ++a;
    cout << a << " " << c << endl;
    int d = 10;
    d %= 3;
    cout << d << endl;
    return 0;
}`
    assertStableRoundtrip(code)
  })

  it('fuzz_5: ternary operator', () => {
    const code = `#include <iostream>
using namespace std;

int main() {
    int a = 3, b = 7;
    int min_val = (a < b) ? a : b;
    cout << min_val << endl;
    int x = 0;
    cout << (x ? 10 : 20) << endl;
    int grade = 85;
    char letter = (grade >= 90) ? 'A' : (grade >= 80) ? 'B' : (grade >= 70) ? 'C' : 'F';
    cout << letter << endl;
    double result = (a > b) ? a : 3.14;
    cout << result << endl;
    cout << (true ? 1 : 2.5) << endl;
    return 0;
}`
    assertStableRoundtrip(code)
  })

  it('fuzz_6: sizeof', () => {
    const code = `#include <iostream>
using namespace std;

int main() {
    cout << sizeof(char) << endl;
    cout << sizeof(int) << endl;
    cout << sizeof(double) << endl;
    cout << sizeof(long long) << endl;
    char c = 'X';
    cout << sizeof(c) << endl;
    cout << sizeof(c + 1) << endl;
    cout << sizeof(3.14f) << endl;
    cout << sizeof(3.14) << endl;
    bool flag = true;
    cout << sizeof(flag) << endl;
    short s = 10;
    cout << sizeof(s + s) << endl;
    return 0;
}`
    assertStableRoundtrip(code)
  })

  it('fuzz_7: bitwise operations', () => {
    const code = `#include <iostream>
using namespace std;

int main() {
    int a = 0b1010;
    int b = 0b1100;
    cout << (a & b) << endl;
    cout << (a | b) << endl;
    cout << (a ^ b) << endl;
    cout << (~0 & 0xFF) << endl;
    int flags = 0;
    flags |= (1 << 0);
    flags |= (1 << 2);
    cout << flags << endl;
    cout << ((flags >> 2) & 1) << endl;
    flags ^= (1 << 0);
    cout << flags << endl;
    unsigned char mask = static_cast<unsigned char>(~0);
    cout << static_cast<int>(mask) << endl;
    return 0;
}`
    assertStableRoundtrip(code)
  })

  it('fuzz_8: enum with custom values', () => {
    const code = `#include <iostream>
using namespace std;

int main() {
    enum Color { RED, GREEN, BLUE };
    Color c = GREEN;
    cout << c << endl;
    enum Status { OK = 200, NOT_FOUND = 404, ERROR = 500 };
    Status s = NOT_FOUND;
    cout << s << endl;
    int val = BLUE + 10;
    cout << val << endl;
    enum Level { LOW = -1, MEDIUM = 0, HIGH = 1 };
    cout << LOW << endl;
    cout << (HIGH > MEDIUM) << endl;
    enum Bits { A = 1, B = 2, C = 4, D = 8 };
    int combined = A | C;
    cout << combined << endl;
    return 0;
}`
    assertStableRoundtrip(code)
  })

  it('fuzz_9: auto and const', () => {
    const code = `#include <iostream>
using namespace std;

int main() {
    const int LIMIT = 100;
    auto sum = 0;
    auto i = 1;
    while (i <= 10 && sum < LIMIT) {
        sum += i * i;
        ++i;
    }
    cout << i << endl;
    cout << sum << endl;
    const double PI = 3.14159;
    auto area = PI * 5 * 5;
    cout << static_cast<int>(area) << endl;
    auto x = 10;
    auto y = 3;
    auto q = x / y;
    cout << q << endl;
    auto z = 10 / 3.0;
    cout << z << endl;
    return 0;
}`
    assertStableRoundtrip(code)
  })

  it('fuzz_10: type casting and overflow', () => {
    const code = `#include <iostream>
using namespace std;

int main() {
    int a = 256 + 65;
    char c = static_cast<char>(a);
    cout << c << endl;
    double d = 9.99;
    int truncated = static_cast<int>(d);
    cout << truncated << endl;
    bool t = true, f = false;
    cout << t + t + f << endl;
    cout << (t && !f) << endl;
    int p = 0, q = 0, r = 0;
    p = 5;
    q = p + 3;
    r = q * 2 - p;
    cout << p << " " << q << " " << r << endl;
    unsigned int u = static_cast<unsigned int>(-1);
    cout << (u > 0) << endl;
    int big = 2000000000;
    int doubled = big + big;
    cout << (doubled < 0) << endl;
    return 0;
}`
    assertStableRoundtrip(code)
  })
})
