/**
 * Fuzz tests for C++ <cstring> concepts
 *
 * Generated by Agent A (information-isolated) — 10 programs testing
 * strlen, strcmp, strcpy, strcat, strncpy, strncmp, strchr, strstr, memset, memcpy
 *
 * 2/10 PASS, 8/10 EXPECTED_DEGRADATION (pre-existing lifter limitations,
 * NOT cstring-specific bugs):
 *   - const qualifier dropped from pointer params
 *   - char s[] = "..." array initializer lost
 *   - while ((x = f()) != null) assignment-in-condition pattern
 *   - pointer declarations in for-loop init
 *   - multi-declaration arrays losing size
 */
import { describe, it, expect, beforeAll } from 'vitest'
import { Parser, Language } from 'web-tree-sitter'
import { createTestLifter } from '../helpers/setup-lifter'
import type { Lifter } from '../../src/core/lift/lifter'
import { registerCppLanguage } from '../../src/languages/cpp/generators'
import { generateCode } from '../../src/core/projection/code-generator'
import { setupTestRenderer } from '../helpers/setup-renderer'
import type { StylePreset } from '../../src/core/types'
import type { SemanticNode } from '../../src/core/semantic-tree'

const style: StylePreset = {
  id: 'apcs',
  name: { 'zh-TW': 'APCS', en: 'APCS' },
  io_style: 'cout',
  naming_convention: 'camelCase',
  indent_size: 4,
  brace_style: 'K&R',
  namespace_style: 'using',
  header_style: 'individual',
}

let tsParser: Parser
let lifter: Lifter

beforeAll(async () => {
  await Parser.init({
    locateFile: (scriptName: string) => `${process.cwd()}/public/${scriptName}`,
  })
  tsParser = new Parser()
  const lang = await Language.load(`${process.cwd()}/public/tree-sitter-cpp.wasm`)
  tsParser.setLanguage(lang)
  lifter = createTestLifter()
  registerCppLanguage()
  setupTestRenderer()
})

function liftCode(code: string): SemanticNode | null {
  const tree = tsParser.parse(code)
  return lifter.lift(tree.rootNode as any)
}

function roundTripCode(code: string): string {
  const tree = liftCode(code)
  expect(tree).not.toBeNull()
  return generateCode(tree!, 'cpp', style)
}

function collectConcepts(node: SemanticNode | null, result: Set<string> = new Set()): Set<string> {
  if (!node) return result
  result.add(node.concept)
  for (const children of Object.values(node.children ?? {})) {
    for (const child of children as SemanticNode[]) {
      collectConcepts(child, result)
    }
  }
  return result
}

describe('Fuzz: C++ <cstring>', () => {

  // fuzz_04: strchr + strstr + strlen — PASS
  it('should roundtrip strchr/strstr/strlen search operations', () => {
    const code = `#include <iostream>
#include <cstring>
using namespace std;
int main() {
    const char* hay = "the quick brown fox jumps over the lazy dog";
    const char* p = strchr(hay, 'q');
    if (p) cout << "first q at index: " << (p - hay) << endl;
    p = strchr(hay, 'z');
    if (p) cout << "first z at index: " << (p - hay) << endl;
    p = strchr(hay, '!');
    cout << "found: " << (p ? "yes" : "no") << endl;
    const char* sub = strstr(hay, "fox");
    if (sub) cout << "fox at: " << (sub - hay) << endl;
    sub = strstr(hay, "the");
    if (sub) {
        cout << "first the at: " << (sub - hay) << endl;
        const char* second = strstr(sub + 1, "the");
        if (second) cout << "second the at: " << (second - hay) << endl;
    }
    cout << "total len: " << strlen(hay) << endl;
    return 0;
}`
    const tree = liftCode(code)
    expect(tree).not.toBeNull()
    const concepts = collectConcepts(tree)
    expect(concepts.has('cpp_strchr')).toBe(true)
    expect(concepts.has('cpp_strstr')).toBe(true)
    expect(concepts.has('cpp_strlen')).toBe(true)
    // Verify roundtrip generates compilable code
    const generated = roundTripCode(code)
    expect(generated).toContain('strchr')
    expect(generated).toContain('strstr')
    expect(generated).toContain('strlen')
  })

  // fuzz_06: strcpy + strcmp bubble sort — PASS
  it('should roundtrip strcpy/strcmp in bubble sort', () => {
    const code = `#include <iostream>
#include <cstring>
using namespace std;
int main() {
    char words[5][20];
    strcpy(words[0], "banana");
    strcpy(words[1], "apple");
    strcpy(words[2], "cherry");
    strcpy(words[3], "date");
    strcpy(words[4], "avocado");
    for (int i = 0; i < 4; i++) {
        for (int j = 0; j < 4 - i; j++) {
            if (strcmp(words[j], words[j + 1]) > 0) {
                char tmp[20];
                strcpy(tmp, words[j]);
                strcpy(words[j], words[j + 1]);
                strcpy(words[j + 1], tmp);
            }
        }
    }
    for (int i = 0; i < 5; i++)
        cout << words[i] << endl;
    return 0;
}`
    const tree = liftCode(code)
    expect(tree).not.toBeNull()
    const concepts = collectConcepts(tree)
    expect(concepts.has('cpp_strcpy')).toBe(true)
    expect(concepts.has('cpp_strcmp')).toBe(true)
    const generated = roundTripCode(code)
    expect(generated).toContain('strcpy')
    expect(generated).toContain('strcmp')
  })

  // fuzz_01: strcpy/strcat/memset with const params — COMPILE_FAIL
  // Root cause: const qualifier dropped from pointer function params (pre-existing lifter limitation)
  it.todo('should preserve const qualifier on pointer function params (fuzz_01: strcpy/strcat/memset)')

  // fuzz_02: strncpy/memset with char array initializer — STDOUT_DIFF
  // Root cause: char s[] = "text" array initializer lost (pre-existing lifter limitation)
  it.todo('should preserve char array string literal initializers (fuzz_02: strncpy/memset)')

  // fuzz_03: strcmp/strncmp with pointer arithmetic — STDOUT_DIFF
  // Root cause: char s[] = "text" initializer lost + const params (pre-existing)
  it.todo('should roundtrip strcmp/strncmp with array initializers (fuzz_03)')

  // fuzz_05: memcpy/memset with char array initializer — STDOUT_DIFF
  // Root cause: char s[] = "text" array initializer lost (pre-existing)
  it.todo('should roundtrip memcpy/memset with initialized char arrays (fuzz_05)')

  // fuzz_07: strcat/strncpy/strcpy tokenization — COMPILE_FAIL
  // Root cause: pointer declaration in for-loop init lost (pre-existing)
  it.todo('should handle pointer declarations in for-loop init (fuzz_07)')

  // fuzz_08: memcpy/memset/strcpy/strncmp packed data — COMPILE_FAIL
  // Root cause: multi-declaration arrays lose size; char a[8],b[8] → char a, char b (pre-existing)
  it.todo('should preserve array sizes in multi-declarations (fuzz_08)')

  // fuzz_09: strchr/strcat/strncpy removeChar — COMPILE_FAIL
  // Root cause: while((found=strchr(...))!=nullptr) assignment-in-condition pattern (pre-existing)
  it.todo('should handle while-assignment-condition pattern (fuzz_09: strchr)')

  // fuzz_10: strstr/memcpy/strcpy replaceAll — COMPILE_FAIL
  // Root cause: while((match=strstr(...))!=nullptr) assignment-in-condition pattern (pre-existing)
  it.todo('should handle while-assignment-condition pattern (fuzz_10: strstr)')
})
