/**
 * Fuzz Test Regression: C++ Control Flow
 * Generated from Phase 2 fuzz testing (2026-03-12)
 *
 * Tests lift → generate → execution roundtrip for programs
 * generated by an isolated agent with no knowledge of Semorphe internals.
 */
import { describe, it, expect, beforeAll } from 'vitest'
import { Parser, Language } from 'web-tree-sitter'
import type { Lifter } from '../../src/core/lift/lifter'
import { registerCppLanguage } from '../../src/languages/cpp/generators'
import { generateCode } from '../../src/core/projection/code-generator'
import { setupTestRenderer } from '../helpers/setup-renderer'
import { createTestLifter } from '../helpers/setup-lifter'
import { SemanticInterpreter } from '../../src/interpreter/interpreter'
import type { StylePreset } from '../../src/core/types'

const style: StylePreset = {
  id: 'apcs',
  name: { 'zh-TW': 'APCS', en: 'APCS' },
  io_style: 'cout',
  naming_convention: 'camelCase',
  indent_size: 4,
  brace_style: 'K&R',
  namespace_style: 'using',
  header_style: 'individual',
}

let tsParser: Parser
let lifter: Lifter

beforeAll(async () => {
  await Parser.init({
    locateFile: (scriptName: string) => `${process.cwd()}/public/${scriptName}`,
  })
  tsParser = new Parser()
  const lang = await Language.load(`${process.cwd()}/public/tree-sitter-cpp.wasm`)
  tsParser.setLanguage(lang)
  lifter = createTestLifter()
  registerCppLanguage()
  setupTestRenderer()
})

async function runCode(code: string) {
  const tree = tsParser.parse(code)
  const sem = lifter.lift(tree.rootNode as any)
  expect(sem).not.toBeNull()
  const interp = new SemanticInterpreter({ maxSteps: 100000 })
  await interp.execute(sem!, [])
  return interp
}

function roundTrip(code: string): string {
  const tree = tsParser.parse(code)
  const sem = lifter.lift(tree.rootNode as any)
  expect(sem).not.toBeNull()
  return generateCode(sem!, 'cpp', style)
}

// ─── PASS programs ───

describe('fuzz: nested for with break', () => {
  const code = `#include <iostream>
using namespace std;
int main() {
    int count = 0;
    for (int i = 0; i < 5; i++) {
        for (int j = 0; j < 5; j++) {
            if (j >= 3) {
                break;
            }
            count = count + 1;
        }
    }
    cout << count << endl;
    return 0;
}`

  it('executes correctly', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('15')
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

describe('fuzz: do-while with compound condition', () => {
  const code = `#include <iostream>
using namespace std;
int main() {
    int x = 1;
    int sum = 0;
    do {
        sum = sum + x;
        x = x + 1;
    } while (x <= 5 && sum < 100);
    cout << sum << endl;
    cout << x << endl;
    return 0;
}`

  it('executes correctly', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('15')
    expect(out).toContain('6')
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

describe('fuzz: continue in for loop', () => {
  const code = `#include <iostream>
using namespace std;
int main() {
    int sum = 0;
    for (int i = 1; i <= 20; i++) {
        if (i % 2 == 0) {
            continue;
        }
        sum = sum + i;
    }
    cout << sum << endl;
    return 0;
}`

  it('executes correctly', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('100')
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

describe('fuzz: function with loop', () => {
  const code = `#include <iostream>
using namespace std;
int factorial(int n) {
    int result = 1;
    for (int i = 1; i <= n; i++) {
        result = result * i;
    }
    return result;
}
int main() {
    cout << factorial(5) << endl;
    cout << factorial(0) << endl;
    return 0;
}`

  it('executes correctly', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('120')
    expect(out).toContain('1')
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

describe('fuzz: while with break and continue', () => {
  const code = `#include <iostream>
using namespace std;
int main() {
    int i = 0;
    int sum = 0;
    while (i < 100) {
        i = i + 1;
        if (i % 5 != 0) {
            continue;
        }
        if (i > 30) {
            break;
        }
        sum = sum + i;
    }
    cout << sum << endl;
    cout << i << endl;
    return 0;
}`

  it('executes correctly', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('105')  // 5+10+15+20+25+30
    expect(out).toContain('35')   // breaks when i=35 (first multiple of 5 > 30)
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

describe('fuzz: nested loops with continue', () => {
  const code = `#include <iostream>
using namespace std;
int main() {
    int count = 0;
    for (int i = 1; i <= 4; i++) {
        for (int j = 1; j <= 4; j++) {
            if (i == j) {
                continue;
            }
            count = count + 1;
        }
    }
    cout << count << endl;
    return 0;
}`

  it('executes correctly', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('12')
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

// ─── Known issues (not in Phase 2 scope) ───

describe.skip('fuzz: switch fall-through (Phase 2 scope, to fix)', () => {
  // COMPILE_FAIL: switch without break causes fall-through behavior
  // that the current lifter does not handle correctly
  it.todo('should handle switch case without break (fall-through)')
})

describe.skip('fuzz: char literals in switch cases (COMPILE_FAIL)', () => {
  // COMPILE_FAIL: char literal case labels (case 'a':) are not
  // correctly lifted by the switch-case lifter
  it.todo('should handle char literal case labels in switch')
})

describe.skip('fuzz: array initializer lists (Phase 4 scope, SEMANTIC_DIFF)', () => {
  // SEMANTIC_DIFF: array initializer lists like int arr[] = {1, 2, 3}
  // are not yet supported in the semantic tree
  it.todo('should handle array initializer list syntax')
})
