/**
 * Fuzz Test Regression: C++ Variables & Operators
 * Generated from Phase 1 fuzz testing (2026-03-12)
 *
 * Tests lift → generate → execution roundtrip for programs
 * generated by an isolated agent with no knowledge of Semorphe internals.
 */
// ⚠️ 091：C++ 的 `cout << (x > 2)` 印出 **1／0**，不是 `true`／`false`
// （後者要 `std::boolalpha`）。這個檔原本的斷言記錄的是**舊的錯誤輸出**，
// 期望值已改為 g++ 實際印出的東西。
import { describe, it, expect, beforeAll } from 'vitest'
import { Parser, Language } from 'web-tree-sitter'
import type { Lifter } from '../../src/core/lift/lifter'
import { registerCppLanguage } from '../../src/languages/cpp/generators'
import { generateCode } from '../../src/core/projection/code-generator'
import { setupTestRenderer } from '../helpers/setup-renderer'
import { createTestLifter } from '../helpers/setup-lifter'
import { SemanticInterpreter } from '../../src/interpreter/interpreter'
import type { StylePreset } from '../../src/core/types'

const style: StylePreset = {
  id: 'apcs',
  name: { 'zh-TW': 'APCS', en: 'APCS' },
  io_style: 'cout',
  naming_convention: 'camelCase',
  indent_size: 4,
  brace_style: 'K&R',
  namespace_style: 'using',
  header_style: 'individual',
}

let tsParser: Parser
let lifter: Lifter

beforeAll(async () => {
  await Parser.init({
    locateFile: (scriptName: string) => `${process.cwd()}/public/${scriptName}`,
  })
  tsParser = new Parser()
  const lang = await Language.load(`${process.cwd()}/public/tree-sitter-cpp.wasm`)
  tsParser.setLanguage(lang)
  lifter = createTestLifter()
  registerCppLanguage()
  setupTestRenderer()
})

async function runCode(code: string) {
  const tree = tsParser.parse(code)
  const sem = lifter.lift(tree.rootNode as any)
  expect(sem).not.toBeNull()
  const interp = new SemanticInterpreter({ maxSteps: 100000 })
  await interp.execute(sem!, [])
  return interp
}

function roundTrip(code: string): string {
  const tree = tsParser.parse(code)
  const sem = lifter.lift(tree.rootNode as any)
  expect(sem).not.toBeNull()
  return generateCode(sem!, 'cpp', style)
}

// ─── PASS programs ───

describe('fuzz: integer division and modulo identity', () => {
  const code = `#include <iostream>
using namespace std;
int main() {
    int a = 7;
    int b = 2;
    int c = a / b;
    int d = a % b;
    int e = a / b * b + a % b;
    cout << c << endl;
    cout << d << endl;
    cout << e << endl;
    return 0;
}`

  it('executes correctly', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('3')
    expect(out).toContain('1')
    expect(out).toContain('7')
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

describe('fuzz: negative division and modulo', () => {
  const code = `#include <iostream>
using namespace std;
int main() {
    int a = -7;
    int b = 2;
    int c = a / b;
    int d = a % b;
    cout << c << endl;
    cout << d << endl;
    int e = 7;
    int f = -2;
    cout << e / f << endl;
    cout << e % f << endl;
    return 0;
}`

  it('executes correctly', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('-3')
    expect(out).toContain('-1')
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

describe('fuzz: int-to-double coercion', () => {
  const code = `#include <iostream>
using namespace std;
int main() {
    int a = 5;
    double b = 2.0;
    double c = a / b;
    cout << c << endl;
    int d = 5;
    int e = 2;
    double f = d / e;
    cout << f << endl;
    double g = (double)d / e;
    cout << g << endl;
    return 0;
}`

  it('executes correctly', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('2.5')
    expect(out).toContain('2')
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

describe('fuzz: comparison and boolean arithmetic', () => {
  const code = `#include <iostream>
using namespace std;
int main() {
    int a = 1;
    int b = 2;
    int c = 3;
    bool r1 = (a < b);
    bool r2 = (a < b) && (b < c);
    cout << r1 << endl;
    cout << r2 << endl;
    int x = (a < b) + (b < c) + (a < c);
    cout << x << endl;
    bool r3 = (a == 1);
    bool r4 = (a != b);
    bool r5 = (a >= b);
    cout << r3 << " " << r4 << " " << r5 << endl;
    return 0;
}`

  it('executes correctly', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('1')  // r1 = true (interpreter prints 'true' not '1')
    expect(out).toContain('3')  // 3 true comparisons
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

describe('fuzz: double negation -(-a)', () => {
  const code = `#include <iostream>
using namespace std;
int main() {
    int a = 5;
    int b = -a;
    int c = -b;
    int d = -(-a);
    cout << b << endl;
    cout << c << endl;
    cout << d << endl;
    int e = -a * 2;
    int f = -(a * 2);
    int g = a * -2;
    cout << e << endl;
    cout << f << endl;
    cout << g << endl;
    cout << -a % 3 << endl;
    return 0;
}`

  it('executes correctly', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('-5')
    expect(out).toContain('5')   // c = -(-5) = 5, d = -(-5) = 5
    expect(out).toContain('-10')
    expect(out).toContain('-2')  // -5 % 3 = -2
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

describe('fuzz: precedence puzzle', () => {
  const code = `#include <iostream>
using namespace std;
int main() {
    int a = 2 + 3 * 4;
    cout << a << endl;
    int b = (2 + 3) * 4;
    cout << b << endl;
    int c = 10 - 4 - 3;
    cout << c << endl;
    int d = 2 * 3 % 4;
    cout << d << endl;
    int e = 2 + 8 / 4 - 1;
    cout << e << endl;
    bool f = 3 + 2 > 4;
    cout << f << endl;
    bool g = 3 + 2 > 4 && 1 + 1 == 2;
    cout << g << endl;
    int h = 10 / 3 * 3 + 10 % 3;
    cout << h << endl;
    return 0;
}`

  it('executes correctly', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('14')  // 2+3*4
    expect(out).toContain('20')  // (2+3)*4
    expect(out).toContain('3')   // 10-4-3
    expect(out).toContain('10')  // 10/3*3+10%3
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

// ─── Known issues (not in Phase 1 scope) ───

describe.skip('[BLOCKED:cpp:print] fuzz: cout with parenthesized boolean expressions (Phase 3 I/O scope)', () => {
  // vars_ops_005: cout << (a && b) loses parens → COMPILE_FAIL
  // vars_ops_009: cout << (f < 0) loses parens → COMPILE_FAIL
  // Root cause: cout chain lifter strips parentheses from boolean subexpressions
})

describe.skip('[BLOCKED:cpp:increment] fuzz: pre/post increment in expressions (Phase 2 scope)', () => {
  // vars_ops_008: int b = a++; has incorrect result in roundtrip
  // Root cause: increment expression handling in variable initializer context
})
