/**
 * C++ cctype Fuzz Regression Tests
 *
 * Generated by dual-agent fuzz testing.
 * Tests cctype concepts: isalpha, isdigit, toupper, tolower.
 */
import { describe, it, expect, beforeAll } from 'vitest'
import { Parser, Language } from 'web-tree-sitter'
import { createTestLifter } from '../helpers/setup-lifter'
import type { Lifter } from '../../src/core/lift/lifter'
import { registerCppLanguage } from '../../src/languages/cpp/generators'
import { generateCode } from '../../src/core/projection/code-generator'
import { setupTestRenderer } from '../helpers/setup-renderer'
import type { StylePreset } from '../../src/core/types'
import type { SemanticNode } from '../../src/core/semantic-tree'

const style: StylePreset = {
  id: 'apcs',
  name: { 'zh-TW': 'APCS', en: 'APCS' },
  io_style: 'cout',
  naming_convention: 'camelCase',
  indent_size: 4,
  brace_style: 'K&R',
  namespace_style: 'using',
  header_style: 'individual',
}

let tsParser: Parser
let lifter: Lifter

beforeAll(async () => {
  await Parser.init({
    locateFile: (scriptName: string) => `${process.cwd()}/public/${scriptName}`,
  })
  tsParser = new Parser()
  const lang = await Language.load(`${process.cwd()}/public/tree-sitter-cpp.wasm`)
  tsParser.setLanguage(lang)
  lifter = createTestLifter()
  registerCppLanguage()
  setupTestRenderer()
})

function countRawCode(node: SemanticNode): number {
  let count = 0
  if (node.concept === 'raw_code' || node.concept === 'cpp_raw_code') count++
  for (const children of Object.values(node.children ?? {})) {
    for (const child of children as SemanticNode[]) count += countRawCode(child)
  }
  return count
}

function treesStructurallyEqual(a: SemanticNode, b: SemanticNode): boolean {
  if (a.concept !== b.concept) return false
  const aKeys = Object.keys(a.children ?? {}).sort()
  const bKeys = Object.keys(b.children ?? {}).sort()
  if (aKeys.length !== bKeys.length) return false
  for (let i = 0; i < aKeys.length; i++) {
    if (aKeys[i] !== bKeys[i]) return false
    const ac = (a.children?.[aKeys[i]] ?? []) as SemanticNode[]
    const bc = (b.children?.[bKeys[i]] ?? []) as SemanticNode[]
    if (ac.length !== bc.length) return false
    for (let j = 0; j < ac.length; j++) {
      if (!treesStructurallyEqual(ac[j], bc[j])) return false
    }
  }
  return true
}

function liftAndGenerate(code: string) {
  const parsed = tsParser.parse(code)
  const tree = lifter.lift(parsed.rootNode as any)
  const generated = tree ? generateCode(tree, 'cpp', style) : ''
  return { tree, generated }
}

describe('cctype fuzz regression', () => {
  describe('PASS — cctype concepts verified', () => {

    it('fuzz_1: isalpha/isdigit character classification loop', () => {
      const code = `#include <iostream>
#include <cctype>
#include <string>
using namespace std;
int main() {
    string text = "H3llo W0rld! 2025";
    int alphaCount = 0, digitCount = 0, otherCount = 0;
    for (int i = 0; i < text.size(); i++) {
        char c = text[i];
        if (isalpha(c)) alphaCount++;
        else if (isdigit(c)) digitCount++;
        else otherCount++;
    }
    cout << "Alpha: " << alphaCount << endl;
    cout << "Digit: " << digitCount << endl;
    cout << "Other: " << otherCount << endl;
    return 0;
}`
      const { tree, generated } = liftAndGenerate(code)
      expect(tree).not.toBeNull()
      expect(countRawCode(tree!)).toBe(0)
      expect(generated).toContain('isalpha(')
      expect(generated).toContain('isdigit(')
      const parsed2 = tsParser.parse(generated)
      const tree2 = lifter.lift(parsed2.rootNode as any)
      expect(treesStructurallyEqual(tree!, tree2!)).toBe(true)
    })

    it('fuzz_2: toupper string conversion function', () => {
      const code = `#include <iostream>
#include <cctype>
#include <string>
using namespace std;
string toUpperCase(string s) {
    for (int i = 0; i < s.size(); i++) s[i] = toupper(s[i]);
    return s;
}
int main() {
    string original = "Hello, World! 123";
    string upper = toUpperCase(original);
    cout << "Original: " << original << endl;
    cout << "Upper: " << upper << endl;
    return 0;
}`
      const { tree, generated } = liftAndGenerate(code)
      expect(tree).not.toBeNull()
      expect(countRawCode(tree!)).toBe(0)
      expect(generated).toContain('toupper(')
      const parsed2 = tsParser.parse(generated)
      const tree2 = lifter.lift(parsed2.rootNode as any)
      expect(treesStructurallyEqual(tree!, tree2!)).toBe(true)
    })

    it('fuzz_3: toggle case with isalpha + toupper + tolower', () => {
      const code = `#include <iostream>
#include <cctype>
#include <string>
using namespace std;
string toggleCase(string s) {
    for (int i = 0; i < s.size(); i++) {
        if (isalpha(s[i])) {
            if (s[i] >= 'a' && s[i] <= 'z') s[i] = toupper(s[i]);
            else s[i] = tolower(s[i]);
        }
    }
    return s;
}
int main() {
    string text = "HeLLo WoRLd!";
    cout << toggleCase(text) << endl;
    return 0;
}`
      const { tree, generated } = liftAndGenerate(code)
      expect(tree).not.toBeNull()
      expect(countRawCode(tree!)).toBe(0)
      const parsed2 = tsParser.parse(generated)
      const tree2 = lifter.lift(parsed2.rootNode as any)
      expect(treesStructurallyEqual(tree!, tree2!)).toBe(true)
    })

    it('fuzz_4: extract digits with isdigit', () => {
      const code = `#include <iostream>
#include <cctype>
#include <string>
using namespace std;
int main() {
    string input = "abc12de3fg45";
    string digits = "";
    int sum = 0;
    for (int i = 0; i < input.size(); i++) {
        if (isdigit(input[i])) {
            digits += input[i];
            sum += input[i] - '0';
        }
    }
    cout << "Digits: " << digits << endl;
    cout << "Sum: " << sum << endl;
    return 0;
}`
      const { tree, generated } = liftAndGenerate(code)
      expect(tree).not.toBeNull()
      expect(countRawCode(tree!)).toBe(0)
      expect(generated).toContain('isdigit(')
      const parsed2 = tsParser.parse(generated)
      const tree2 = lifter.lift(parsed2.rootNode as any)
      expect(treesStructurallyEqual(tree!, tree2!)).toBe(true)
    })

    it('fuzz_5: capitalize first letter of each word', () => {
      const code = `#include <iostream>
#include <cctype>
#include <string>
using namespace std;
string capitalizeWords(string s) {
    bool newWord = true;
    for (int i = 0; i < s.size(); i++) {
        if (isalpha(s[i])) {
            if (newWord) { s[i] = toupper(s[i]); newWord = false; }
            else { s[i] = tolower(s[i]); }
        } else { newWord = true; }
    }
    return s;
}
int main() {
    string text = "hELLO wORLD fOO bAR";
    cout << capitalizeWords(text) << endl;
    return 0;
}`
      const { tree, generated } = liftAndGenerate(code)
      expect(tree).not.toBeNull()
      expect(countRawCode(tree!)).toBe(0)
      const parsed2 = tsParser.parse(generated)
      const tree2 = lifter.lift(parsed2.rootNode as any)
      expect(treesStructurallyEqual(tree!, tree2!)).toBe(true)
    })

    it('fuzz_7: Caesar cipher with isalpha guard', () => {
      const code = `#include <iostream>
#include <cctype>
#include <string>
using namespace std;
string caesarCipher(string text, int shift) {
    string result = "";
    for (int i = 0; i < text.size(); i++) {
        char c = text[i];
        if (isalpha(c)) {
            char base = (c >= 'a' && c <= 'z') ? 'a' : 'A';
            c = base + (c - base + shift) % 26;
        }
        result += c;
    }
    return result;
}
int main() {
    string message = "Hello, World! Xyz";
    string encrypted = caesarCipher(message, 3);
    cout << "Original:  " << message << endl;
    cout << "Encrypted: " << encrypted << endl;
    return 0;
}`
      const { tree, generated } = liftAndGenerate(code)
      expect(tree).not.toBeNull()
      expect(countRawCode(tree!)).toBe(0)
      expect(generated).toContain('isalpha(')
      const parsed2 = tsParser.parse(generated)
      const tree2 = lifter.lift(parsed2.rootNode as any)
      expect(treesStructurallyEqual(tree!, tree2!)).toBe(true)
    })

    it('fuzz_8: character frequency with toupper comparison', () => {
      const code = `#include <iostream>
#include <cctype>
#include <string>
using namespace std;
int main() {
    string data = "Cpp2025! Test99XyZ";
    int upper = 0, lower = 0, digit = 0;
    for (int i = 0; i < data.size(); i++) {
        char c = data[i];
        if (isalpha(c)) {
            if (toupper(c) == c) upper++;
            else lower++;
        } else if (isdigit(c)) digit++;
    }
    cout << "String: " << data << endl;
    cout << "Uppercase: " << upper << endl;
    cout << "Lowercase: " << lower << endl;
    cout << "Digits: " << digit << endl;
    cout << "Total chars: " << data.size() << endl;
    return 0;
}`
      const { tree, generated } = liftAndGenerate(code)
      expect(tree).not.toBeNull()
      expect(countRawCode(tree!)).toBe(0)
      const parsed2 = tsParser.parse(generated)
      const tree2 = lifter.lift(parsed2.rootNode as any)
      expect(treesStructurallyEqual(tree!, tree2!)).toBe(true)
    })
  })

  describe('known lifter limitations (not cctype-specific)', () => {
    it.todo('fuzz_6: validate identifier — string array initializer lost (pre-existing lifter limitation)')
    it.todo('fuzz_9: palindrome check — string array initializer lost (pre-existing lifter limitation)')
    it.todo('fuzz_10: character classification — int array initializer {0,0,0} lost (pre-existing lifter limitation)')
  })
})
