/**
 * C++ cstdlib Fuzz Regression Tests
 *
 * Generated by dual-agent fuzz testing (Agent A: isolated, Agent B: verifier).
 * Tests cstdlib concepts: rand, srand, abs, exit, atoi, atof.
 * code → lift → generate → re-lift → structural equivalence.
 */
import { describe, it, expect, beforeAll } from 'vitest'
import { Parser, Language } from 'web-tree-sitter'
import { createTestLifter } from '../helpers/setup-lifter'
import type { Lifter } from '../../src/core/lift/lifter'
import { registerCppLanguage } from '../../src/languages/cpp/generators'
import { generateCode } from '../../src/core/projection/code-generator'
import { setupTestRenderer } from '../helpers/setup-renderer'
import type { StylePreset } from '../../src/core/types'
import type { SemanticNode } from '../../src/core/semantic-tree'

const style: StylePreset = {
  id: 'apcs',
  name: { 'zh-TW': 'APCS', en: 'APCS' },
  io_style: 'cout',
  naming_convention: 'camelCase',
  indent_size: 4,
  brace_style: 'K&R',
  namespace_style: 'using',
  header_style: 'individual',
}

let tsParser: Parser
let lifter: Lifter

beforeAll(async () => {
  await Parser.init({
    locateFile: (scriptName: string) => `${process.cwd()}/public/${scriptName}`,
  })
  tsParser = new Parser()
  const lang = await Language.load(`${process.cwd()}/public/tree-sitter-cpp.wasm`)
  tsParser.setLanguage(lang)
  lifter = createTestLifter()
  registerCppLanguage()
  setupTestRenderer()
})

function countRawCode(node: SemanticNode): number {
  let count = 0
  if (node.concept === 'raw_code' || node.concept === 'cpp_raw_code') count++
  for (const children of Object.values(node.children ?? {})) {
    for (const child of children as SemanticNode[]) {
      count += countRawCode(child)
    }
  }
  return count
}

function treesStructurallyEqual(a: SemanticNode, b: SemanticNode): boolean {
  if (a.concept !== b.concept) return false
  const aKeys = Object.keys(a.children ?? {}).sort()
  const bKeys = Object.keys(b.children ?? {}).sort()
  if (aKeys.length !== bKeys.length) return false
  for (let i = 0; i < aKeys.length; i++) {
    if (aKeys[i] !== bKeys[i]) return false
    const ac = (a.children?.[aKeys[i]] ?? []) as SemanticNode[]
    const bc = (b.children?.[bKeys[i]] ?? []) as SemanticNode[]
    if (ac.length !== bc.length) return false
    for (let j = 0; j < ac.length; j++) {
      if (!treesStructurallyEqual(ac[j], bc[j])) return false
    }
  }
  return true
}

function liftAndGenerate(code: string) {
  const parsed = tsParser.parse(code)
  const tree = lifter.lift(parsed.rootNode as any)
  const generated = tree ? generateCode(tree, 'cpp', style) : ''
  return { tree, generated }
}

describe('cstdlib fuzz regression', () => {
  describe('PASS — cstdlib concepts verified', () => {

    it('fuzz_1: rand with fixed seed and modular arithmetic + abs', () => {
      const code = `#include <iostream>
#include <cstdlib>
using namespace std;

int normalize(int val, int range) {
    return abs(val % range);
}

int main() {
    srand(42);
    int sum = 0;
    for (int i = 0; i < 5; i++) {
        int r = rand() % 201 - 100;
        int n = normalize(r, 50);
        sum += n;
        cout << "raw=" << r << " norm=" << n << endl;
    }
    cout << "sum=" << sum << endl;
    return 0;
}`
      const { tree, generated } = liftAndGenerate(code)
      expect(tree).not.toBeNull()
      expect(countRawCode(tree!)).toBe(0)
      expect(generated).toContain('srand(')
      expect(generated).toContain('rand()')
      expect(generated).toContain('abs(')

      const parsed2 = tsParser.parse(generated)
      const tree2 = lifter.lift(parsed2.rootNode as any)
      expect(tree2).not.toBeNull()
      expect(treesStructurallyEqual(tree!, tree2!)).toBe(true)
    })

    it('fuzz_2: atoi and atof with string literals and arithmetic', () => {
      const code = `#include <iostream>
#include <cstdlib>
using namespace std;

int main() {
    const char* vals[] = {"123", "-45", "0", "99", "007"};
    int intSum = 0;
    for (int i = 0; i < 5; i++) {
        int v = atoi(vals[i]);
        intSum += v;
        cout << "atoi(\\"" << vals[i] << "\\") = " << v << endl;
    }
    cout << "intSum = " << intSum << endl;

    const char* fvals[] = {"3.14", "-2.7", "0.001", "100.0"};
    double fSum = 0.0;
    for (int i = 0; i < 4; i++) {
        double d = atof(fvals[i]);
        fSum += d;
        cout << "atof(\\"" << fvals[i] << "\\") = " << d << endl;
    }
    cout << "fSum = " << fSum << endl;
    return 0;
}`
      const { tree, generated } = liftAndGenerate(code)
      expect(tree).not.toBeNull()
      expect(countRawCode(tree!)).toBe(0)
      expect(generated).toContain('atoi(')
      expect(generated).toContain('atof(')

      const parsed2 = tsParser.parse(generated)
      const tree2 = lifter.lift(parsed2.rootNode as any)
      expect(tree2).not.toBeNull()
      expect(treesStructurallyEqual(tree!, tree2!)).toBe(true)
    })

    it('fuzz_6: atoi for command simulation with do-while and break', () => {
      const code = `#include <iostream>
#include <cstdlib>
using namespace std;

int main() {
    const char* commands[] = {"5", "12", "-1", "3", "0"};
    int idx = 0;
    int accumulator = 100;
    do {
        int op = atoi(commands[idx]);
        if (op < 0) {
            cout << "halt at index " << idx << endl;
            break;
        }
        if (op == 0) {
            cout << "skip at index " << idx << endl;
            idx++;
            continue;
        }
        accumulator -= op;
        cout << "op=" << op << " acc=" << accumulator << endl;
        idx++;
    } while (idx < 5);
    cout << "final=" << accumulator << endl;
    return 0;
}`
      const { tree, generated } = liftAndGenerate(code)
      expect(tree).not.toBeNull()
      expect(countRawCode(tree!)).toBe(0)
      expect(generated).toContain('atoi(')

      const parsed2 = tsParser.parse(generated)
      const tree2 = lifter.lift(parsed2.rootNode as any)
      expect(tree2).not.toBeNull()
      expect(treesStructurallyEqual(tree!, tree2!)).toBe(true)
    })

    it('fuzz_7: shadowed variable with abs and nested loops', () => {
      const code = `#include <iostream>
#include <cstdlib>
using namespace std;

int main() {
    int val = -10;
    cout << "outer val=" << val << endl;
    for (int i = 0; i < 3; i++) {
        int val = abs(i * 7 - 10);
        int total = 0;
        for (int j = 1; j <= val; j += 3) {
            total += j;
        }
        cout << "i=" << i << " inner_val=" << val << " total=" << total << endl;
    }
    cout << "outer val still=" << val << endl;
    cout << "abs(val)=" << abs(val) << endl;
    return 0;
}`
      const { tree, generated } = liftAndGenerate(code)
      expect(tree).not.toBeNull()
      expect(countRawCode(tree!)).toBe(0)
      expect(generated).toContain('abs(')

      const parsed2 = tsParser.parse(generated)
      const tree2 = lifter.lift(parsed2.rootNode as any)
      expect(tree2).not.toBeNull()
      expect(treesStructurallyEqual(tree!, tree2!)).toBe(true)
    })

    it('fuzz_8: rand-driven array fill with function returning abs difference', () => {
      const code = `#include <iostream>
#include <cstdlib>
using namespace std;

int absDiff(int a, int b) {
    return abs(a - b);
}

int main() {
    srand(7);
    const int N = 6;
    int arr[N];
    for (int i = 0; i < N; i++) {
        arr[i] = rand() % 50;
        cout << "arr[" << i << "]=" << arr[i] << endl;
    }
    int minDiff = absDiff(arr[0], arr[1]);
    int minIdx = 0;
    for (int i = 1; i < N - 1; i++) {
        int d = absDiff(arr[i], arr[i + 1]);
        if (d < minDiff) {
            minDiff = d;
            minIdx = i;
        }
    }
    cout << "min diff=" << minDiff << " between indices " << minIdx << " and " << minIdx + 1 << endl;
    return 0;
}`
      const { tree, generated } = liftAndGenerate(code)
      expect(tree).not.toBeNull()
      expect(countRawCode(tree!)).toBe(0)
      expect(generated).toContain('srand(')
      expect(generated).toContain('rand()')
      expect(generated).toContain('abs(')

      const parsed2 = tsParser.parse(generated)
      const tree2 = lifter.lift(parsed2.rootNode as any)
      expect(tree2).not.toBeNull()
      expect(treesStructurallyEqual(tree!, tree2!)).toBe(true)
    })
  })

  describe('known lifter limitations (not cstdlib-specific)', () => {

    it.todo('fuzz_3: exit in helper function — array initializer {10, 25, 0, -3, 99} lost (pre-existing lifter limitation: array initializer values not preserved)')

    it.todo('fuzz_4: abs with function chaining — array initializer {-20, 5, 0, 15, -8, 30} lost (pre-existing lifter limitation: array initializer values not preserved)')

    it.todo('fuzz_5: srand/rand with switch — array initializer {0, 0, 0} lost (pre-existing lifter limitation: array initializer values not preserved)')

    it.todo('fuzz_9: atof with comma operator — comma operator in condition (result = num / den, true) not supported (pre-existing lifter limitation: comma operator in expressions)')

    it.todo('fuzz_10: exit with multiple functions — array initializer {50, 65, 30, 95, 45} lost (pre-existing lifter limitation: array initializer values not preserved)')
  })
})
