/**
 * Fuzz Test Regression: C++ Functions & I/O
 * Generated from fuzz testing (2026-03-12)
 *
 * Tests lift -> generate -> execution roundtrip for programs
 * generated by an isolated agent with no knowledge of Semorphe internals.
 */
import { describe, it, expect, beforeAll } from 'vitest'
import { Parser, Language } from 'web-tree-sitter'
import type { Lifter } from '../../src/core/lift/lifter'
import { registerCppLanguage } from '../../src/languages/cpp/generators'
import { generateCode } from '../../src/core/projection/code-generator'
import { setupTestRenderer } from '../helpers/setup-renderer'
import { createTestLifter } from '../helpers/setup-lifter'
import { SemanticInterpreter } from '../../src/interpreter/interpreter'
import type { StylePreset } from '../../src/core/types'

const style: StylePreset = {
  id: 'apcs',
  name: { 'zh-TW': 'APCS', en: 'APCS' },
  io_style: 'cout',
  naming_convention: 'camelCase',
  indent_size: 4,
  brace_style: 'K&R',
  namespace_style: 'using',
  header_style: 'individual',
}

let tsParser: Parser
let lifter: Lifter

beforeAll(async () => {
  await Parser.init({
    locateFile: (scriptName: string) => `${process.cwd()}/public/${scriptName}`,
  })
  tsParser = new Parser()
  const lang = await Language.load(`${process.cwd()}/public/tree-sitter-cpp.wasm`)
  tsParser.setLanguage(lang)
  lifter = createTestLifter()
  registerCppLanguage()
  setupTestRenderer()
})

async function runCode(code: string) {
  const tree = tsParser.parse(code)
  const sem = lifter.lift(tree.rootNode as any)
  expect(sem).not.toBeNull()
  const interp = new SemanticInterpreter({ maxSteps: 100000 })
  await interp.execute(sem!, [])
  return interp
}

function roundTrip(code: string): string {
  const tree = tsParser.parse(code)
  const sem = lifter.lift(tree.rootNode as any)
  expect(sem).not.toBeNull()
  return generateCode(sem!, 'cpp', style)
}

// --- PASS programs ---

describe('fuzz: functions calling functions (sumOfSquares)', () => {
  const code = `#include <iostream>
using namespace std;
int square(int x) {
    return x * x;
}
int sumOfSquares(int a, int b) {
    return square(a) + square(b);
}
int main() {
    cout << sumOfSquares(3, 4) << endl;
    cout << sumOfSquares(0, 5) << endl;
    return 0;
}`

  it('executes correctly', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('25')
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

describe('fuzz: recursive power function', () => {
  const code = `#include <iostream>
using namespace std;
int power(int base, int exp) {
    if (exp == 0) {
        return 1;
    }
    return base * power(base, exp - 1);
}
int main() {
    cout << power(2, 10) << endl;
    cout << power(3, 0) << endl;
    cout << power(5, 3) << endl;
    return 0;
}`

  it('executes correctly', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('1024')
    expect(out).toContain('125')
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

describe('fuzz: void function with loop (printLine)', () => {
  const code = `#include <iostream>
using namespace std;
void printLine(int n, int ch) {
    for (int i = 0; i < n; i++) {
        cout << ch;
    }
    cout << endl;
}
int main() {
    printLine(5, 1);
    printLine(3, 0);
    return 0;
}`

  it('executes correctly', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('11111')
    expect(out).toContain('000')
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

describe('fuzz: nested function calls as arguments (maxOfThree)', () => {
  const code = `#include <iostream>
using namespace std;
int maxVal(int a, int b) {
    if (a > b) {
        return a;
    }
    return b;
}
int maxOfThree(int a, int b, int c) {
    return maxVal(maxVal(a, b), c);
}
int main() {
    cout << maxOfThree(3, 7, 5) << endl;
    cout << maxOfThree(10, 2, 8) << endl;
    cout << maxOfThree(1, 1, 1) << endl;
    return 0;
}`

  it('executes correctly', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('7')
    expect(out).toContain('10')
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

describe('fuzz: global variable with void/value functions (counter)', () => {
  const code = `#include <iostream>
using namespace std;
int counter = 0;
void tick() {
    counter = counter + 1;
}
int getCount() {
    return counter;
}
int main() {
    tick();
    tick();
    tick();
    cout << getCount() << endl;
    tick();
    tick();
    cout << getCount() << endl;
    return 0;
}`

  it('executes correctly', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('3')
    expect(out).toContain('5')
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

describe('fuzz: return value used in expressions (sumRange)', () => {
  const code = `#include <iostream>
using namespace std;
int sumRange(int lo, int hi) {
    int s = 0;
    for (int i = lo; i <= hi; i++) {
        s = s + i;
    }
    return s;
}
int main() {
    cout << sumRange(1, 10) << endl;
    cout << sumRange(5, 5) << endl;
    int x = sumRange(1, 5) + sumRange(6, 10);
    cout << x << endl;
    return 0;
}`

  it('executes correctly', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('55')
    expect(out).toContain('5')
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

describe('fuzz: #define macro constant + function (collatzSteps)', () => {
  const code = `#include <iostream>
using namespace std;
#define LIMIT 100
int collatzSteps(int n) {
    int steps = 0;
    while (n != 1) {
        if (n % 2 == 0) {
            n = n / 2;
        } else {
            n = 3 * n + 1;
        }
        steps = steps + 1;
        if (steps > LIMIT) {
            return -1;
        }
    }
    return steps;
}
int main() {
    cout << collatzSteps(6) << endl;
    cout << collatzSteps(27) << endl;
    cout << collatzSteps(1) << endl;
    return 0;
}`

  // Interpreter does not expand #define macros into scope, so execution fails
  // with RUNTIME_ERR_UNDECLARED_VAR for LIMIT. Roundtrip + g++ compilation works.
  it.skip('[TOMBSTONE:014-墓碑目錄#模擬-c-preprocessor-來解決巨集] executes correctly (interpreter lacks #define expansion)', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('8')
    expect(out).toContain('-1')
    expect(out).toContain('0')
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

describe('fuzz: bool function + function calling function (countEven)', () => {
  const code = `#include <iostream>
using namespace std;
bool isEven(int n) {
    if (n % 2 == 0) {
        return true;
    }
    return false;
}
int countEven(int lo, int hi) {
    int c = 0;
    for (int i = lo; i <= hi; i++) {
        if (isEven(i)) {
            c = c + 1;
        }
    }
    return c;
}
int main() {
    cout << countEven(1, 10) << endl;
    cout << countEven(2, 2) << endl;
    cout << countEven(1, 1) << endl;
    return 0;
}`

  it('executes correctly', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('5')
    expect(out).toContain('1')
    expect(out).toContain('0')
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

describe('fuzz: cout chaining mixed types + expressions in cout', () => {
  const code = `#include <iostream>
using namespace std;
int abs_val(int x) {
    if (x < 0) {
        return -x;
    }
    return x;
}
int main() {
    int a = 10;
    int b = 3;
    int q = a / b;
    int r = a % b;
    cout << q << " " << r << endl;
    cout << abs_val(-42) << endl;
    cout << abs_val(7) << endl;
    cout << q * b + r << endl;
    return 0;
}`

  it('executes correctly', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('3 1')
    expect(out).toContain('42')
    expect(out).toContain('7')
    expect(out).toContain('10')
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

describe('fuzz: nested function calls as arguments (apply_twice)', () => {
  const code = `#include <iostream>
using namespace std;
int apply_twice(int x, int n) {
    for (int i = 0; i < n; i++) {
        x = x * 2;
    }
    return x;
}
int main() {
    int result = apply_twice(1, 3) + apply_twice(2, 2);
    cout << result << endl;
    int a = apply_twice(apply_twice(1, 2), 3);
    cout << a << endl;
    cout << apply_twice(0, 10) << endl;
    return 0;
}`

  it('executes correctly', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('16')
    expect(out).toContain('32')
    expect(out).toContain('0')
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

// --- Known issues (regression) ---

describe.skip('[DEADSKIP] fuzz: char literal in function return (fixed)', () => {
})
