/**
 * C++ String Fuzz Tests
 *
 * Generated by /concept.fuzz cpp hard string 10 on 2026-03-13.
 * Agent A (isolated) generated 10 programs; Agent B verified roundtrip.
 *
 * ⚠️ 2026-08-06 更正：下面這段檔頭宣稱**已被實證推翻**，保留原文以記錄轉變。
 *
 *   原文：「ALL tests are currently it.todo because the failures stem from a
 *   pre-existing cout lifter limitation (complex cout << chain not recognized
 *   as `print` concept)... Enable when: cout lifter can handle
 *   `cout << method_call() << endl;`」
 *
 * 實測（specs/050-repay-top-blockers/research.md F1）：
 *   cout << s.substr(0,3) << endl  →  print { values: [cpp_string_substr, endl] }
 * **它認得出來，運算元的概念身分完整保留。** 那個阻斷條件已經不成立。
 *
 * 而逐筆註解顯示根因**各不相同**（條件中的賦值、const 遺失、vector 初始化
 * 列表、未支援的字串函式）——檔頭的「ALL ... because」從一開始就過度概括。
 *
 * 教訓：**檔案層級的概括會過期，也會一開始就錯；逐筆註解才是一手記錄。**
 * 沒有獨立證據支持的歸因，已改標 [UNVERIFIED]——寧可承認不知道。
 */
import { describe, it, expect, beforeAll } from 'vitest'
import { Parser, Language } from 'web-tree-sitter'
import { createTestLifter } from '../helpers/setup-lifter'
import type { Lifter } from '../../src/core/lift/lifter'
import { registerCppLanguage } from '../../src/languages/cpp/generators'
import { generateCode } from '../../src/core/projection/code-generator'
import { setupTestRenderer } from '../helpers/setup-renderer'
import type { StylePreset } from '../../src/core/types'
import type { SemanticNode } from '../../src/core/semantic-tree'

const style: StylePreset = {
  id: 'apcs',
  name: { 'zh-TW': 'APCS', en: 'APCS' },
  io_style: 'cout',
  naming_convention: 'camelCase',
  indent_size: 4,
  brace_style: 'K&R',
  namespace_style: 'using',
  header_style: 'individual',
}

let tsParser: Parser
let lifter: Lifter

beforeAll(async () => {
  await Parser.init({
    locateFile: (scriptName: string) => `${process.cwd()}/public/${scriptName}`,
  })
  tsParser = new Parser()
  const lang = await Language.load(`${process.cwd()}/public/tree-sitter-cpp.wasm`)
  tsParser.setLanguage(lang)
  lifter = createTestLifter()
  registerCppLanguage()
  setupTestRenderer()
})

function liftCode(code: string): SemanticNode | null {
  const tree = tsParser.parse(code)
  return lifter.lift(tree.rootNode as any)
}

function roundTripCode(code: string): string {
  const tree = liftCode(code)
  expect(tree).not.toBeNull()
  return generateCode(tree!, 'cpp', style)
}

// ⚠️ 這個檔原本有六支標成 `[UNVERIFIED]` 的 todo——**連停用理由都不知道**。
//
// 086 逐一寫程式、用 g++ 定期望值、餵進直譯器，追出**四個疊在一起的缺陷**：
// 字串宣告忽略初始值、比較不比內容、push_back 讀錯子槽、字元字面掉型別。
//
// 四個都修好了，回歸測試在 `tests/integration/string-value-semantics.test.ts`
// ——那裡每一支都驗**執行結果**，期望值由 g++ 實際編譯執行決定。
//
// 這個檔剩下的 todo 是別的阻斷者，各自還在。

describe('C++ String Fuzz Tests (hard)', () => {
  // All tests blocked by: cout lifter cannot handle complex cout << chain
  // (e.g. cout << s.substr(s.length() - 1) << endl;)
  // ROUNDTRIP_DRIFT — cout << s.substr(s.length() - 1) << endl becomes raw_code
  // ROUNDTRIP_DRIFT — cout << s << endl after mutations becomes raw_code
  // COMPILE_FAIL — while ((pos = s.find(...)) != npos) generates malformed code
  // COMPILE_FAIL — cout chains with conversion results become raw_code
  // COMPILE_FAIL — cout with ternary and function calls in chain

  it.todo('[BLOCKED:cpp_pointer_declare] fuzz_6: function returning substr with nested find')
  // COMPILE_FAIL — function with const reference params drops const
  // COMPILE_FAIL — cout << inside if/else blocks with string comparisons
  // ROUNDTRIP_DRIFT — s.clear() after cout << becomes chained

  it.todo('[UNSUPPORTED:vector 的初始化列表語法尚無對應概念] fuzz_9: vector<string> with join function')
  // COMPILE_FAIL — vector initializer_list syntax not supported

  it.todo('[UNSUPPORTED:字串搜尋函式 find_first_not_of／find_last_not_of 尚無對應概念] fuzz_10: multi-step string transformation (trim/collapse/replace)')
  // COMPILE_FAIL — find_first_not_of/find_last_not_of not supported as concepts
})
