/**
 * C++ numeric Fuzz Regression Tests
 *
 * Generated by dual-agent fuzz testing.
 * Tests numeric concepts: accumulate, iota, partial_sum, gcd, lcm.
 */
import { describe, it, expect, beforeAll } from 'vitest'
import { Parser, Language } from 'web-tree-sitter'
import { createTestLifter } from '../helpers/setup-lifter'
import type { Lifter } from '../../src/core/lift/lifter'
import { registerCppLanguage } from '../../src/languages/cpp/generators'
import { generateCode } from '../../src/core/projection/code-generator'
import { setupTestRenderer } from '../helpers/setup-renderer'
import type { StylePreset } from '../../src/core/types'
import type { SemanticNode } from '../../src/core/semantic-tree'

const style: StylePreset = {
  id: 'apcs',
  name: { 'zh-TW': 'APCS', en: 'APCS' },
  io_style: 'cout',
  naming_convention: 'camelCase',
  indent_size: 4,
  brace_style: 'K&R',
  namespace_style: 'using',
  header_style: 'individual',
}

let tsParser: Parser
let lifter: Lifter

beforeAll(async () => {
  await Parser.init({
    locateFile: (scriptName: string) => `${process.cwd()}/public/${scriptName}`,
  })
  tsParser = new Parser()
  const lang = await Language.load(`${process.cwd()}/public/tree-sitter-cpp.wasm`)
  tsParser.setLanguage(lang)
  lifter = createTestLifter()
  registerCppLanguage()
  setupTestRenderer()
})

function countRawCode(node: SemanticNode): number {
  let count = 0
  if (node.concept === 'raw_code' || node.concept === 'cpp_raw_code') count++
  for (const children of Object.values(node.children ?? {})) {
    for (const child of children as SemanticNode[]) count += countRawCode(child)
  }
  return count
}

function treesStructurallyEqual(a: SemanticNode, b: SemanticNode): boolean {
  if (a.concept !== b.concept) return false
  const aKeys = Object.keys(a.children ?? {}).sort()
  const bKeys = Object.keys(b.children ?? {}).sort()
  if (aKeys.length !== bKeys.length) return false
  for (let i = 0; i < aKeys.length; i++) {
    if (aKeys[i] !== bKeys[i]) return false
    const ac = (a.children?.[aKeys[i]] ?? []) as SemanticNode[]
    const bc = (b.children?.[bKeys[i]] ?? []) as SemanticNode[]
    if (ac.length !== bc.length) return false
    for (let j = 0; j < ac.length; j++) {
      if (!treesStructurallyEqual(ac[j], bc[j])) return false
    }
  }
  return true
}

function liftAndGenerate(code: string) {
  const parsed = tsParser.parse(code)
  const tree = lifter.lift(parsed.rootNode as any)
  const generated = tree ? generateCode(tree, 'cpp', style) : ''
  return { tree, generated }
}

describe('numeric fuzz regression', () => {
  describe('PASS — numeric concepts verified', () => {

    it('fuzz_1: accumulate with multiplies functor', () => {
      const code = `#include <iostream>
#include <numeric>
#include <vector>
using namespace std;
int factorial_product(vector<int>& nums, int init) {
    return accumulate(nums.begin(), nums.end(), init, multiplies<int>());
}
int main() {
    vector<int> v = {1, 2, 3, 4, 5};
    int result = factorial_product(v, 1);
    cout << "Product: " << result << endl;
    vector<int> w = {2, 3, 4};
    int scaled = factorial_product(w, 10);
    cout << "Scaled product: " << scaled << endl;
    vector<int> empty;
    int base = factorial_product(empty, 42);
    cout << "Empty with init 42: " << base << endl;
    return 0;
}`
      const { tree, generated } = liftAndGenerate(code)
      expect(tree).not.toBeNull()
      expect(countRawCode(tree!)).toBe(0)
      expect(generated).toContain('accumulate(')
      const parsed2 = tsParser.parse(generated)
      const tree2 = lifter.lift(parsed2.rootNode as any)
      expect(treesStructurallyEqual(tree!, tree2!)).toBe(true)
    })

    it('fuzz_2: iota negative start + partial_sum + accumulate', () => {
      const code = `#include <iostream>
#include <numeric>
#include <vector>
using namespace std;
int main() {
    vector<int> v(7);
    iota(v.begin(), v.end(), -3);
    cout << "Sequence:";
    for (int x : v) {
        cout << " " << x;
    }
    cout << endl;
    vector<int> ps(7);
    partial_sum(v.begin(), v.end(), ps.begin());
    cout << "Partial sums:";
    for (int x : ps) {
        cout << " " << x;
    }
    cout << endl;
    int total = accumulate(v.begin(), v.end(), 0);
    cout << "Total: " << total << endl;
    return 0;
}`
      const { tree, generated } = liftAndGenerate(code)
      expect(tree).not.toBeNull()
      expect(countRawCode(tree!)).toBe(0)
      expect(generated).toContain('iota(')
      expect(generated).toContain('partial_sum(')
      expect(generated).toContain('accumulate(')
      const parsed2 = tsParser.parse(generated)
      const tree2 = lifter.lift(parsed2.rootNode as any)
      expect(treesStructurallyEqual(tree!, tree2!)).toBe(true)
    })

    it('fuzz_3: gcd chain across vector', () => {
      const code = `#include <iostream>
#include <numeric>
#include <vector>
using namespace std;
int array_gcd(const vector<int>& nums) {
    int result = nums[0];
    for (int i = 1; i < (int)nums.size(); i++) {
        result = gcd(result, nums[i]);
    }
    return result;
}
int main() {
    vector<int> a = {12, 18, 24, 36};
    cout << "GCD of {12,18,24,36}: " << array_gcd(a) << endl;
    vector<int> b = {7, 14, 21};
    cout << "GCD of {7,14,21}: " << array_gcd(b) << endl;
    vector<int> c = {100, 75, 50, 25};
    cout << "GCD of {100,75,50,25}: " << array_gcd(c) << endl;
    return 0;
}`
      const { tree, generated } = liftAndGenerate(code)
      expect(tree).not.toBeNull()
      expect(countRawCode(tree!)).toBe(0)
      const parsed2 = tsParser.parse(generated)
      const tree2 = lifter.lift(parsed2.rootNode as any)
      expect(treesStructurallyEqual(tree!, tree2!)).toBe(true)
    })

    it('fuzz_5: partial_sum for range sum queries', () => {
      const code = `#include <iostream>
#include <numeric>
#include <vector>
using namespace std;
int range_sum(const vector<int>& prefix, int l, int r) {
    if (l == 0) {
        return prefix[r];
    }
    return prefix[r] - prefix[l - 1];
}
int main() {
    vector<int> data = {3, 1, 4, 1, 5, 9, 2, 6};
    vector<int> prefix(data.size());
    partial_sum(data.begin(), data.end(), prefix.begin());
    cout << "Data:";
    for (int x : data) {
        cout << " " << x;
    }
    cout << endl;
    cout << "Sum [0,3]: " << range_sum(prefix, 0, 3) << endl;
    cout << "Sum [2,5]: " << range_sum(prefix, 2, 5) << endl;
    cout << "Sum [0,7]: " << range_sum(prefix, 0, 7) << endl;
    cout << "Sum [4,4]: " << range_sum(prefix, 4, 4) << endl;
    return 0;
}`
      const { tree, generated } = liftAndGenerate(code)
      expect(tree).not.toBeNull()
      expect(countRawCode(tree!)).toBe(0)
      expect(generated).toContain('partial_sum(')
      const parsed2 = tsParser.parse(generated)
      const tree2 = lifter.lift(parsed2.rootNode as any)
      expect(treesStructurallyEqual(tree!, tree2!)).toBe(true)
    })

    it('fuzz_6: accumulate with conditional lambda', () => {
      const code = `#include <iostream>
#include <numeric>
#include <vector>
using namespace std;
int main() {
    vector<int> nums = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
    int even_sum = accumulate(nums.begin(), nums.end(), 0,
        [](int total, int val) {
            if (val % 2 == 0) {
                return total + val;
            }
            return total;
        });
    int odd_sum = accumulate(nums.begin(), nums.end(), 0,
        [](int total, int val) {
            if (val % 2 != 0) {
                return total + val;
            }
            return total;
        });
    cout << "Even sum: " << even_sum << endl;
    cout << "Odd sum: " << odd_sum << endl;
    cout << "Total: " << even_sum + odd_sum << endl;
    return 0;
}`
      const { tree, generated } = liftAndGenerate(code)
      expect(tree).not.toBeNull()
      expect(countRawCode(tree!)).toBe(0)
      expect(generated).toContain('accumulate(')
      const parsed2 = tsParser.parse(generated)
      const tree2 = lifter.lift(parsed2.rootNode as any)
      expect(treesStructurallyEqual(tree!, tree2!)).toBe(true)
    })

    it('fuzz_7: iota + gcd coprime pairs', () => {
      const code = `#include <iostream>
#include <numeric>
#include <vector>
using namespace std;
int main() {
    vector<int> indices(6);
    iota(indices.begin(), indices.end(), 1);
    int coprime_count = 0;
    for (int i = 0; i < (int)indices.size(); i++) {
        for (int j = i + 1; j < (int)indices.size(); j++) {
            int a = indices[i];
            int b = indices[j];
            if (gcd(a, b) == 1) {
                cout << a << " and " << b << " are coprime" << endl;
                coprime_count++;
            }
        }
    }
    cout << "Total coprime pairs: " << coprime_count << endl;
    return 0;
}`
      const { tree, generated } = liftAndGenerate(code)
      expect(tree).not.toBeNull()
      expect(countRawCode(tree!)).toBe(0)
      expect(generated).toContain('iota(')
      const parsed2 = tsParser.parse(generated)
      const tree2 = lifter.lift(parsed2.rootNode as any)
      expect(treesStructurallyEqual(tree!, tree2!)).toBe(true)
    })

    it('fuzz_8: partial_sum with multiplies + accumulate consistency', () => {
      const code = `#include <iostream>
#include <numeric>
#include <vector>
#include <functional>
using namespace std;
void print_vector(const string& label, const vector<int>& v) {
    cout << label << ":";
    for (int x : v) {
        cout << " " << x;
    }
    cout << endl;
}
int main() {
    vector<int> v = {1, 2, 3, 4, 5};
    print_vector("Input", v);
    vector<int> sums(v.size());
    partial_sum(v.begin(), v.end(), sums.begin());
    print_vector("Partial sums", sums);
    vector<int> products(v.size());
    partial_sum(v.begin(), v.end(), products.begin(), multiplies<int>());
    print_vector("Running products", products);
    int total = accumulate(v.begin(), v.end(), 0);
    cout << "Sum equals last partial sum: ";
    if (total == sums.back()) {
        cout << "yes" << endl;
    } else {
        cout << "no" << endl;
    }
    return 0;
}`
      const { tree, generated } = liftAndGenerate(code)
      expect(tree).not.toBeNull()
      expect(countRawCode(tree!)).toBe(0)
      const parsed2 = tsParser.parse(generated)
      const tree2 = lifter.lift(parsed2.rootNode as any)
      expect(treesStructurallyEqual(tree!, tree2!)).toBe(true)
    })

    it('fuzz_9: accumulate with gcd/lcm lambdas', () => {
      const code = `#include <iostream>
#include <numeric>
#include <vector>
using namespace std;
int main() {
    vector<int> nums = {12, 18, 24};
    int g = accumulate(nums.begin(), nums.end(), nums[0],
        [](int a, int b) { return gcd(a, b); });
    cout << "GCD of all: " << g << endl;
    long long l = accumulate(nums.begin(), nums.end(), (long long)nums[0],
        [](long long a, int b) { return lcm(a, (long long)b); });
    cout << "LCM of all: " << l << endl;
    for (int i = 0; i < (int)nums.size(); i++) {
        for (int j = i + 1; j < (int)nums.size(); j++) {
            int a = nums[i];
            int b = nums[j];
            int product = a * b;
            int g2 = gcd(a, b);
            int l2 = lcm(a, b);
            cout << a << "*" << b << "=" << product;
            cout << " gcd*lcm=" << g2 * l2 << endl;
        }
    }
    return 0;
}`
      const { tree, generated } = liftAndGenerate(code)
      expect(tree).not.toBeNull()
      expect(countRawCode(tree!)).toBe(0)
      const parsed2 = tsParser.parse(generated)
      const tree2 = lifter.lift(parsed2.rootNode as any)
      expect(treesStructurallyEqual(tree!, tree2!)).toBe(true)
    })
  })

  describe('known lifter limitations (not numeric-specific)', () => {
    it.todo('fuzz_4: lcm chain with C-style array initializer — array initializer {2,3,4,5} lost (pre-existing lifter limitation)')
    it.todo('fuzz_10: struct + iota + accumulate — struct type handling in function params incomplete (pre-existing lifter limitation)')
  })
})
