/**
 * Fuzz Test Regression: C++ Type System & Advanced Operations
 * Generated from fuzz testing (2026-03-12)
 *
 * Tests lift -> generate -> execution roundtrip for programs
 * generated by an isolated agent with no knowledge of Semorphe internals.
 */
import { describe, it, expect, beforeAll } from 'vitest'
import { Parser, Language } from 'web-tree-sitter'
import type { Lifter } from '../../src/core/lift/lifter'
import { registerCppLanguage } from '../../src/languages/cpp/generators'
import { generateCode } from '../../src/core/projection/code-generator'
import { setupTestRenderer } from '../helpers/setup-renderer'
import { createTestLifter } from '../helpers/setup-lifter'
import { SemanticInterpreter } from '../../src/interpreter/interpreter'
import type { StylePreset } from '../../src/core/types'

const style: StylePreset = {
  id: 'apcs',
  name: { 'zh-TW': 'APCS', en: 'APCS' },
  io_style: 'cout',
  naming_convention: 'camelCase',
  indent_size: 4,
  brace_style: 'K&R',
  namespace_style: 'using',
  header_style: 'individual',
}

let tsParser: Parser
let lifter: Lifter

beforeAll(async () => {
  await Parser.init({
    locateFile: (scriptName: string) => `${process.cwd()}/public/${scriptName}`,
  })
  tsParser = new Parser()
  const lang = await Language.load(`${process.cwd()}/public/tree-sitter-cpp.wasm`)
  tsParser.setLanguage(lang)
  lifter = createTestLifter()
  registerCppLanguage()
  setupTestRenderer()
})

async function runCode(code: string) {
  const tree = tsParser.parse(code)
  const sem = lifter.lift(tree.rootNode as any)
  expect(sem).not.toBeNull()
  const interp = new SemanticInterpreter({ maxSteps: 100000 })
  await interp.execute(sem!, [])
  return interp
}

function roundTrip(code: string): string {
  const tree = tsParser.parse(code)
  const sem = lifter.lift(tree.rootNode as any)
  expect(sem).not.toBeNull()
  return generateCode(sem!, 'cpp', style)
}

// --- PASS programs ---

describe('fuzz: ternary operator nested and in expressions', () => {
  const code = `#include <iostream>
using namespace std;
int main() {
    int a = 10;
    int b = 20;
    int c = (a > b) ? a : b;
    cout << c << endl;
    int d = (a < b) ? (a + b) : (a - b);
    cout << d << endl;
    int e = (a > 5) ? ((b > 15) ? 1 : 2) : 3;
    cout << e << endl;
    return 0;
}`

  it('executes correctly', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('20')
    expect(out).toContain('30')
    expect(out).toContain('1')
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

describe('fuzz: C-style cast with int/double/char conversions', () => {
  const code = `#include <iostream>
using namespace std;
int main() {
    double x = 3.14;
    int a = (int)x;
    cout << a << endl;
    int b = 65;
    char c = (char)b;
    cout << c << endl;
    char d = 'Z';
    int e = (int)d;
    cout << e << endl;
    double f = (double)a;
    cout << f << endl;
    return 0;
}`

  it('executes correctly', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('3')   // (int)3.14 = 3
    expect(out).toContain('90')  // (int)'Z' = 90
    // Note: interpreter outputs numeric value for (char)65, not 'A'
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

describe('fuzz: compound assignment operators', () => {
  const code = `#include <iostream>
using namespace std;
int main() {
    int a = 10;
    a += 5;
    cout << a << endl;
    a -= 3;
    cout << a << endl;
    a *= 2;
    cout << a << endl;
    a /= 6;
    cout << a << endl;
    a %= 3;
    cout << a << endl;
    double b = 2.5;
    b += 1.5;
    cout << b << endl;
    return 0;
}`

  it('executes correctly', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('15')
    expect(out).toContain('12')
    expect(out).toContain('24')
    expect(out).toContain('4')
    expect(out).toContain('1')
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

describe('fuzz: sizeof on various types and expressions', () => {
  const code = `#include <iostream>
using namespace std;
int main() {
    cout << sizeof(int) << endl;
    cout << sizeof(double) << endl;
    cout << sizeof(char) << endl;
    cout << sizeof(bool) << endl;
    int arr[5];
    cout << sizeof(arr) / sizeof(arr[0]) << endl;
    return 0;
}`

  it('executes correctly', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('4')
    expect(out).toContain('8')
    expect(out).toContain('1')
    // Note: sizeof(arr)/sizeof(arr[0]) returns 1 in interpreter (no real memory model)
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

describe('fuzz: typedef and using for type aliases', () => {
  const code = `#include <iostream>
using namespace std;
typedef int Integer;
typedef double Real;
using UInt = unsigned int;
int main() {
    Integer a = 42;
    Real b = 3.14;
    UInt c = 100;
    cout << a << endl;
    cout << b << endl;
    cout << c << endl;
    return 0;
}`

  it('executes correctly', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('42')
    expect(out).toContain('3.14')
    expect(out).toContain('100')
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

describe('fuzz: bitwise NOT (~) on integers', () => {
  const code = `#include <iostream>
using namespace std;
int main() {
    int a = 0;
    int b = ~a;
    cout << b << endl;
    int c = 255;
    int d = ~c;
    cout << d << endl;
    int e = ~(~a);
    cout << e << endl;
    return 0;
}`

  it('executes correctly', async () => {
    const interp = await runCode(code)
    const out = interp.getOutput().join('')
    expect(out).toContain('-1')
    expect(out).toContain('-256')
    expect(out).toContain('0')
  })

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

describe('fuzz: mixed enum + ternary + cast + compound assign + bitwise NOT (roundtrip only)', () => {
  const code = `#include <iostream>
using namespace std;
enum Direction { NORTH = 0, EAST = 1, SOUTH = 2, WEST = 3 };
int main() {
    int val = 42;
    int result = (val > 50) ? (int)(val * 1.5) : (int)(val * 0.5);
    cout << result << endl;
    Direction dir = SOUTH;
    int steps = 0;
    switch (dir) {
        case NORTH: steps = 10; break;
        case EAST: steps = 20; break;
        case SOUTH: steps = 30; break;
        case WEST: steps = 40; break;
    }
    cout << steps << endl;
    int counter = 0;
    counter += 5;
    counter *= 3;
    counter -= 1;
    cout << counter << endl;
    int neg = ~0;
    cout << neg << endl;
    return 0;
}`

  // Note: interpreter cannot resolve enum constants (SOUTH) as variable values
  // Execution test skipped; roundtrip code generation verified via fuzz runner

  it('roundtrip is stable', () => {
    const gen1 = roundTrip(code)
    const gen2 = roundTrip(gen1)
    expect(gen1).toBe(gen2)
  })
})

// --- 🪦 曾經的「已知問題」——2026-09-19 逐條覆核，三根【全部是死的】 ---

/**
 * 🔴 **三根 `describe.skip` 在這裡躺了半年，而它們底下的每一件事都早就修好了。**
 *
 * 管線 197 的第五關逐條覆核時量到的（拿 g++ 當權威，四個形狀全綠）：
 *
 * ```
 * (char)65           g++ A      我們 A     🟢
 * sizeof(a)/sizeof(a[0])  g++ 5      我們 5     🟢
 * enum 常數當值       g++ 1      我們 1     🟢
 * int b = ++a;       g++ 22     我們 22    🟢   而且是不動點
 * enum { APPLE = 10 } g++ 10 20  我們 10 20 🟢
 * ```
 *
 * ⚠️ **三根都是「只有標題、沒有本體」**——所以它們**不會在修好的那天變紅**。
 * 缺陷帳自己把這一類叫做 `DEADSKIP`：**已修好卻沒開回來，白白損失覆蓋。**
 *
 * > **一個只有標題的停用測試，與一個修好了的缺陷長得一模一樣
 * > ——而它們的差別只有去跑一次才知道。**
 *
 * 🟢 這也是 `it.fails` 比 `it.todo` 好的理由：**它會在修好的那天自己變紅。**
 */
describe('🪦 三根死釘子（拔掉的那天補上的測試）', () => {
  it('轉型：`(char)65` 印出字元，不是數字', async () => {
    const i = await runCode(`#include <bits/stdc++.h>
using namespace std;
int main() {
  cout << (char)65 << char(66);
  return 0;
}
`)
    expect(i.getOutput().join('')).toBe('AB')
  })

  it('`sizeof(a)/sizeof(a[0])` 算得出陣列長度', async () => {
    const i = await runCode(`#include <bits/stdc++.h>
using namespace std;
int main() {
  int a[5] = {0, 0, 0, 0, 0};
  cout << sizeof(a) / sizeof(a[0]);
  return 0;
}
`)
    expect(i.getOutput().join('')).toBe('5')
  })

  it('列舉常數當值讀得到', async () => {
    const i = await runCode(`#include <bits/stdc++.h>
using namespace std;
enum D { N, S };
int main() {
  cout << S;
  return 0;
}
`)
    expect(i.getOutput().join('')).toBe('1')
  })

  /** 🔴 原本的症狀是「前置遞增被拆成兩句，產出多一個分號」——所以**不動點也要驗**。 */
  it('前置遞增當初值：值對，而且是不動點', async () => {
    const code = `#include <bits/stdc++.h>
using namespace std;
int main() {
  int a = 1;
  int b = ++a;
  int c = 1;
  int d = ++c * 2;
  cout << a << b << c << d;
  return 0;
}
`
    const i = await runCode(code)
    expect(i.getOutput().join('')).toBe('2224')
    const once = roundTrip(code)
    expect(roundTrip(once), '🔴 產出的碼再 lift 一次就走樣').toBe(once)
  })

  it('列舉的明寫值不得被吃掉', async () => {
    const code = `#include <bits/stdc++.h>
using namespace std;
enum Fruit { APPLE = 10, BANANA = 20 };
int main() {
  cout << APPLE << " " << BANANA;
  return 0;
}
`
    const i = await runCode(code)
    expect(i.getOutput().join('')).toBe('10 20')
    expect(roundTrip(code), '🔴 明寫的值在產出的碼裡不見了').toContain('APPLE = 10')
  })
})
