/**
 * C++ Algorithm Fuzz Tests
 *
 * Generated by dual-agent fuzz testing. Agent A (isolated) wrote realistic C++
 * programs using algorithm functions; Agent B verified roundtrip correctness.
 *
 * All algorithm concepts (cpp_sort, cpp_reverse, cpp_fill, cpp_min, cpp_max,
 * cpp_swap) lift and generate correctly. Compilation failures are due to
 * unsupported adjacent features (pair type, lambda comparators, initializer
 * list min/max, min_element/max_element, vector initializer lists, etc.).
 */
import { describe, it, expect, beforeAll } from 'vitest'
import { Parser, Language } from 'web-tree-sitter'
import { createTestLifter } from '../helpers/setup-lifter'
import type { Lifter } from '../../src/core/lift/lifter'
import { registerCppLanguage } from '../../src/languages/cpp/generators'
import { generateCode } from '../../src/core/projection/code-generator'
import { setupTestRenderer } from '../helpers/setup-renderer'
import type { StylePreset } from '../../src/core/types'
import type { SemanticNode } from '../../src/core/semantic-tree'

const style: StylePreset = {
  id: 'apcs',
  name: { 'zh-TW': 'APCS', en: 'APCS' },
  io_style: 'cout',
  naming_convention: 'camelCase',
  indent_size: 4,
  brace_style: 'K&R',
  namespace_style: 'using',
  header_style: 'individual',
}

let tsParser: Parser
let lifter: Lifter

beforeAll(async () => {
  await Parser.init({
    locateFile: (scriptName: string) => `${process.cwd()}/public/${scriptName}`,
  })
  tsParser = new Parser()
  const lang = await Language.load(`${process.cwd()}/public/tree-sitter-cpp.wasm`)
  tsParser.setLanguage(lang)
  lifter = createTestLifter()
  registerCppLanguage()
  setupTestRenderer()
})

function liftCode(code: string): SemanticNode | null {
  const tree = tsParser.parse(code)
  return lifter.lift(tree.rootNode as any)
}

function roundTripCode(code: string): string {
  const tree = liftCode(code)
  expect(tree).not.toBeNull()
  return generateCode(tree!, 'cpp', style)
}

function collectConcepts(node: SemanticNode | null, result: Set<string> = new Set()): Set<string> {
  if (!node) return result
  result.add(node.concept)
  for (const children of Object.values(node.children ?? {})) {
    for (const child of children as SemanticNode[]) {
      collectConcepts(child, result)
    }
  }
  return result
}

describe('C++ Algorithm Fuzz Tests', () => {

  describe('fuzz_1: sort with partial reverse (pair type degraded)', () => {
    // Original uses pair<int,int> and lambda comparator — pair/lambda not supported
    // Test: verify sort and reverse are detected even with unsupported pair types
    const code = 'vector<pair<int,int>> v = {{3,5},{1,5}};\nsort(v.begin(), v.end());\nreverse(v.begin(), v.begin() + 1);\ncout << "done" << endl;'

    it('should lift sort and reverse concepts', () => {
      const tree = liftCode(code)
      const concepts = collectConcepts(tree)
      expect(concepts.has('cpp_sort')).toBe(true)
      expect(concepts.has('cpp_reverse')).toBe(true)
    })

    it('should survive P1 structural equivalence for algo concepts', () => {
      const output = roundTripCode(code)
      const tree2 = liftCode(output)
      const concepts2 = collectConcepts(tree2)
      expect(concepts2.has('cpp_sort')).toBe(true)
      expect(concepts2.has('cpp_reverse')).toBe(true)
    })
  })

  describe('fuzz_2: fill + min + max + swap on C-style arrays', () => {
    // Simplified: use vectors instead of C-style arrays for compilable roundtrip
    const code = 'vector<int> a;\na.push_back(10);\na.push_back(10);\na.push_back(3);\nint x = min(a[0], a[2]);\nint y = max(a[0], a[2]);\ncout << x << " " << y << endl;\nswap(x, y);\ncout << x << " " << y << endl;'

    it('should lift min, max, and swap concepts', () => {
      const tree = liftCode(code)
      const concepts = collectConcepts(tree)
      expect(concepts.has('cpp_min')).toBe(true)
      expect(concepts.has('cpp_max')).toBe(true)
      expect(concepts.has('cpp_swap')).toBe(true)
    })

    it('should survive P1 structural equivalence', () => {
      const output = roundTripCode(code)
      const tree2 = liftCode(output)
      const concepts2 = collectConcepts(tree2)
      expect(concepts2.has('cpp_min')).toBe(true)
      expect(concepts2.has('cpp_max')).toBe(true)
      expect(concepts2.has('cpp_swap')).toBe(true)
    })
  })

  describe('fuzz_3: recursive sort + reverse (func_def)', () => {
    // Test lift of function using sort/reverse inside body
    const code = 'void doSort(vector<int>& v, int left, int right, bool ascending) {\n    sort(v.begin() + left, v.begin() + right);\n    if (!ascending) {\n        reverse(v.begin() + left, v.begin() + right);\n    }\n}\nvector<int> v;\nv.push_back(9);\nv.push_back(1);\nv.push_back(8);\nv.push_back(2);\ndoSort(v, 0, 4, true);\nfor (int i = 0; i < v.size(); i++) {\n    cout << v[i] << " ";\n}\ncout << endl;'

    it('should lift sort and reverse inside function definition', () => {
      const tree = liftCode(code)
      const concepts = collectConcepts(tree)
      expect(concepts.has('cpp_sort')).toBe(true)
      expect(concepts.has('cpp_reverse')).toBe(true)
      expect(concepts.has('func_def')).toBe(true)
    })

    it('should survive P1 structural equivalence', () => {
      const output = roundTripCode(code)
      const tree2 = liftCode(output)
      const concepts2 = collectConcepts(tree2)
      expect(concepts2.has('cpp_sort')).toBe(true)
      expect(concepts2.has('cpp_reverse')).toBe(true)
    })
  })

  describe('fuzz_4: fill + sort on 2D grid', () => {
    // Simplified: fill and sort on single vector
    const code = 'vector<int> row;\nrow.push_back(0);\nrow.push_back(0);\nrow.push_back(0);\nrow.push_back(0);\nfill(row.begin(), row.end(), 10);\nrow[0] = 3;\nsort(row.begin(), row.end());\nfor (int i = 0; i < row.size(); i++) {\n    cout << row[i] << " ";\n}\ncout << endl;'

    it('should lift fill and sort concepts', () => {
      const tree = liftCode(code)
      const concepts = collectConcepts(tree)
      expect(concepts.has('cpp_fill')).toBe(true)
      expect(concepts.has('cpp_sort')).toBe(true)
    })

    it('should survive P1 structural equivalence', () => {
      const output = roundTripCode(code)
      const tree2 = liftCode(output)
      const concepts2 = collectConcepts(tree2)
      expect(concepts2.has('cpp_fill')).toBe(true)
      expect(concepts2.has('cpp_sort')).toBe(true)
    })
  })

  describe('fuzz_5: chained swap + overlapping sort + reverse', () => {
    const code = 'vector<int> v;\nv.push_back(50);\nv.push_back(40);\nv.push_back(30);\nv.push_back(20);\nint a = 10;\nint b = 20;\nswap(a, b);\ncout << a << " " << b << endl;\nsort(v.begin(), v.end());\nreverse(v.begin(), v.end());\nfor (int i = 0; i < v.size(); i++) {\n    cout << v[i] << " ";\n}\ncout << endl;'

    it('should lift swap, sort, and reverse', () => {
      const tree = liftCode(code)
      const concepts = collectConcepts(tree)
      expect(concepts.has('cpp_swap')).toBe(true)
      expect(concepts.has('cpp_sort')).toBe(true)
      expect(concepts.has('cpp_reverse')).toBe(true)
    })

    it('should survive P1 structural equivalence', () => {
      const output = roundTripCode(code)
      const tree2 = liftCode(output)
      const concepts2 = collectConcepts(tree2)
      expect(concepts2.has('cpp_swap')).toBe(true)
      expect(concepts2.has('cpp_sort')).toBe(true)
      expect(concepts2.has('cpp_reverse')).toBe(true)
    })
  })

  describe('fuzz_6: sort in function + min/max + reverse', () => {
    const code = 'vector<int> a;\na.push_back(4);\na.push_back(7);\na.push_back(1);\nsort(a.begin(), a.end());\nint m = min(a[0], a[2]);\nint M = max(a[0], a[2]);\ncout << m << " " << M << endl;\nreverse(a.begin(), a.end());\nfor (int i = 0; i < a.size(); i++) {\n    cout << a[i] << " ";\n}\ncout << endl;'

    it('should lift sort, min, max, and reverse', () => {
      const tree = liftCode(code)
      const concepts = collectConcepts(tree)
      expect(concepts.has('cpp_sort')).toBe(true)
      expect(concepts.has('cpp_min')).toBe(true)
      expect(concepts.has('cpp_max')).toBe(true)
      expect(concepts.has('cpp_reverse')).toBe(true)
    })

    it('should survive P1 structural equivalence', () => {
      const output = roundTripCode(code)
      const tree2 = liftCode(output)
      const concepts2 = collectConcepts(tree2)
      expect(concepts2.has('cpp_sort')).toBe(true)
      expect(concepts2.has('cpp_min')).toBe(true)
      expect(concepts2.has('cpp_max')).toBe(true)
      expect(concepts2.has('cpp_reverse')).toBe(true)
    })
  })

  describe('fuzz_7: bubble sort swap + fill + sort + reverse', () => {
    // Test swap inside nested loops + fill partial range + sort + reverse
    const code = 'vector<int> v;\nv.push_back(64);\nv.push_back(34);\nv.push_back(25);\nv.push_back(12);\nv.push_back(22);\nfor (int i = 0; i < 5; i++) {\n    for (int j = 0; j + 1 < 5 - i; j++) {\n        if (v[j] > v[j + 1]) {\n            swap(v[j], v[j + 1]);\n        }\n    }\n}\nfill(v.begin() + 1, v.begin() + 4, 0);\nsort(v.begin(), v.end());\nreverse(v.begin(), v.end());\nfor (int i = 0; i < v.size(); i++) {\n    cout << v[i] << " ";\n}\ncout << endl;'

    it('should lift swap, fill, sort, and reverse', () => {
      const tree = liftCode(code)
      const concepts = collectConcepts(tree)
      expect(concepts.has('cpp_swap')).toBe(true)
      expect(concepts.has('cpp_fill')).toBe(true)
      expect(concepts.has('cpp_sort')).toBe(true)
      expect(concepts.has('cpp_reverse')).toBe(true)
    })

    it('should survive P1 structural equivalence', () => {
      const output = roundTripCode(code)
      const tree2 = liftCode(output)
      const concepts2 = collectConcepts(tree2)
      expect(concepts2.has('cpp_swap')).toBe(true)
      expect(concepts2.has('cpp_fill')).toBe(true)
      expect(concepts2.has('cpp_sort')).toBe(true)
      expect(concepts2.has('cpp_reverse')).toBe(true)
    })
  })

  describe('fuzz_8: sort + unique-erase idiom (unique/erase degraded)', () => {
    // unique and erase idiom not supported — test that sort still lifts
    const code = 'vector<int> v;\nv.push_back(3);\nv.push_back(1);\nv.push_back(4);\nv.push_back(1);\nv.push_back(5);\nsort(v.begin(), v.end());\nfor (int i = 0; i < v.size(); i++) {\n    cout << v[i] << " ";\n}\ncout << endl;'

    it('should lift sort concept', () => {
      const tree = liftCode(code)
      const concepts = collectConcepts(tree)
      expect(concepts.has('cpp_sort')).toBe(true)
    })

    it('should survive P1 structural equivalence', () => {
      const output = roundTripCode(code)
      const tree2 = liftCode(output)
      const concepts2 = collectConcepts(tree2)
      expect(concepts2.has('cpp_sort')).toBe(true)
    })
  })

  describe('fuzz_9: swap in quickselect partition + sort + min + max', () => {
    // Simplified: swap in loop + sort + min + max
    const code = 'vector<int> v;\nv.push_back(12);\nv.push_back(3);\nv.push_back(5);\nv.push_back(7);\nint pivot = v[3];\nint idx = 0;\nfor (int j = 0; j < 3; j++) {\n    if (v[j] <= pivot) {\n        swap(v[idx], v[j]);\n        idx = idx + 1;\n    }\n}\nsort(v.begin(), v.end());\ncout << min(v[0], v[3]) << endl;\ncout << max(v[0], v[3]) << endl;'

    it('should lift swap, sort, min, and max', () => {
      const tree = liftCode(code)
      const concepts = collectConcepts(tree)
      expect(concepts.has('cpp_swap')).toBe(true)
      expect(concepts.has('cpp_sort')).toBe(true)
      expect(concepts.has('cpp_min')).toBe(true)
      expect(concepts.has('cpp_max')).toBe(true)
    })

    it('should survive P1 structural equivalence', () => {
      const output = roundTripCode(code)
      const tree2 = liftCode(output)
      const concepts2 = collectConcepts(tree2)
      expect(concepts2.has('cpp_swap')).toBe(true)
      expect(concepts2.has('cpp_sort')).toBe(true)
      expect(concepts2.has('cpp_min')).toBe(true)
      expect(concepts2.has('cpp_max')).toBe(true)
    })
  })

  describe('fuzz_10: all 6 algo concepts together', () => {
    const code = 'vector<int> v;\nv.push_back(42);\nv.push_back(17);\nv.push_back(93);\nv.push_back(8);\nsort(v.begin(), v.end());\nreverse(v.begin(), v.end());\nfill(v.begin(), v.begin() + 2, 0);\nint a = 10;\nint b = 20;\nswap(a, b);\ncout << min(a, b) << " " << max(a, b) << endl;\nfor (int i = 0; i < v.size(); i++) {\n    cout << v[i] << " ";\n}\ncout << endl;'

    it('should lift all 6 algorithm concepts', () => {
      const tree = liftCode(code)
      const concepts = collectConcepts(tree)
      expect(concepts.has('cpp_sort')).toBe(true)
      expect(concepts.has('cpp_reverse')).toBe(true)
      expect(concepts.has('cpp_fill')).toBe(true)
      expect(concepts.has('cpp_swap')).toBe(true)
      expect(concepts.has('cpp_min')).toBe(true)
      expect(concepts.has('cpp_max')).toBe(true)
    })

    it('should survive P1 structural equivalence', () => {
      const output = roundTripCode(code)
      const tree2 = liftCode(output)
      const concepts2 = collectConcepts(tree2)
      expect(concepts2.has('cpp_sort')).toBe(true)
      expect(concepts2.has('cpp_reverse')).toBe(true)
      expect(concepts2.has('cpp_fill')).toBe(true)
      expect(concepts2.has('cpp_swap')).toBe(true)
      expect(concepts2.has('cpp_min')).toBe(true)
      expect(concepts2.has('cpp_max')).toBe(true)
    })
  })
})
